'use client';

import { useMemo, useState } from 'react';
import { Download, FileText, Pencil, Plus, Search, Trash2, Upload, X } from 'lucide-react';

export type WebFormSubmission={
 id:string;submissionId:string;submittedAtUtc:string;submittedAtIst:string;submissionType:string;formName:string;sourcePage:string;
 fullName:string;email:string;phone:string;company:string;website:string;message:string;growthTarget:string;preferredDate:string;preferredTime:string;
 positionApplied:string;department:string;experience:string;currentCompany:string;location:string;resumeLink:string;portfolioLink:string;
 resumeFilename:string;resumeMimeType:string;resumeSizeBytes:string;ipAddress:string;userAgent:string;referrer:string;deliveryNotes:string;
 quality?:'Good'|'Bad'|'Neutral';createdAt:string;updatedAt:string;
};

type WebFormField=Exclude<keyof WebFormSubmission,'id'|'quality'|'createdAt'|'updatedAt'>;
const columns:[WebFormField,string][]=[
 ['submissionId','Submission ID'],['submittedAtUtc','Submitted At (UTC)'],['submittedAtIst','Submitted At (IST)'],['submissionType','Submission Type'],
 ['formName','Form / Popup Name'],['sourcePage','Source Page'],['fullName','Full Name'],['email','Email'],['phone','Phone'],['company','Company'],
 ['website','Website'],['message','Message / Details'],['growthTarget','Growth Target'],['preferredDate','Preferred Date'],['preferredTime','Preferred Time'],
 ['positionApplied','Position Applied'],['department','Department'],['experience','Experience'],['currentCompany','Current Company'],['location','Location'],
 ['resumeLink','Resume Link'],['portfolioLink','Portfolio Link'],['resumeFilename','Resume Filename'],['resumeMimeType','Resume MIME Type'],
 ['resumeSizeBytes','Resume Size (Bytes)'],['ipAddress','IP Address'],['userAgent','User Agent'],['referrer','Referrer'],['deliveryNotes','Delivery Notes'],
];
const blank=():WebFormSubmission=>{const stamp=new Date().toISOString();return Object.fromEntries([['id',crypto.randomUUID()],...columns.map(([key])=>[key,'']),['quality','Neutral'],['createdAt',stamp],['updatedAt',stamp]]) as WebFormSubmission};
const input='h-10 w-full rounded-xl border border-white/10 bg-[#101012] px-3 py-2 text-sm text-white outline-none focus:border-[#f16133]';
const format=(value:string)=>value?new Date(value).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'}):'—';

export function WebFormsSection({records,setRecords}:{records:WebFormSubmission[];setRecords:React.Dispatch<React.SetStateAction<WebFormSubmission[]>>}){
 const [query,setQuery]=useState(''),[limit,setLimit]=useState(10),[editing,setEditing]=useState<WebFormSubmission|null|undefined>();
 const rows=useMemo(()=>records.filter(item=>columns.some(([key])=>item[key].toLowerCase().includes(query.toLowerCase()))).slice(0,limit),[records,query,limit]);
 const save=(record:WebFormSubmission)=>{const next={...record,submissionId:record.submissionId||record.id,createdAt:record.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};setRecords(value=>editing?value.map(item=>item.id===next.id?next:item):[next,...value]);setEditing(undefined)};
 const quality=(item:WebFormSubmission,value:string)=>setRecords(records=>records.map(record=>record.id===item.id?{...record,quality:value as WebFormSubmission['quality'],updatedAt:new Date().toISOString()}:record));
 const remove=(item:WebFormSubmission)=>{if(confirm(`Delete submission ${item.submissionId||item.fullName}?`))setRecords(records=>records.filter(record=>record.id!==item.id))};
 return <div className="grid gap-4">
  <div className="grid grid-cols-2 gap-2 sm:flex sm:flex-wrap">
   <label className="col-span-2 flex h-10 min-w-52 flex-1 items-center gap-2 rounded-xl border border-white/10 bg-[#151517] px-3"><Search size={16} className="text-zinc-500"/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search web form submissions" className="min-w-0 w-full bg-transparent text-sm outline-none"/></label>
   <Export records={records}/><Import onImport={incoming=>setRecords(current=>merge(current,incoming))}/>
   <label className="flex h-10 items-center justify-center gap-2 rounded-xl border border-white/10 bg-[#151517] px-3 text-[10px] font-bold text-zinc-400">Show<select value={limit} onChange={event=>setLimit(Number(event.target.value))} className="bg-transparent text-white outline-none">{[10,25,50].map(size=><option key={size} className="bg-[#151517]">{size}</option>)}</select></label>
   <button onClick={()=>setEditing(null)} className="flex h-10 items-center justify-center gap-2 rounded-xl bg-[#f16133] px-4 text-xs font-bold"><Plus size={15}/> Add submission</button>
  </div>
  <div className="grid gap-3 lg:hidden md:grid-cols-2">{rows.map(item=><article key={item.id} className="min-w-0 rounded-2xl border border-white/10 bg-[#151517] p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-[9px] font-bold uppercase tracking-wider text-[#f16133]">{item.submissionType||'Web submission'}</p><h3 className="mt-1 truncate font-display text-lg font-bold">{item.fullName||item.company||'Unnamed submission'}</h3><p className="truncate text-[10px] text-zinc-500">{item.email||item.phone||'No contact details'}</p></div><select aria-label={`Quality for ${item.fullName||item.submissionId}`} value={item.quality||'Neutral'} onChange={event=>quality(item,event.target.value)} className="h-8 shrink-0 rounded-lg border border-white/10 bg-[#101012] px-2 text-[10px] text-white outline-none"><option>Good</option><option>Neutral</option><option>Bad</option></select></div><dl className="mt-4 grid grid-cols-2 gap-3 text-[10px]"><div><dt className="text-zinc-600">Submission ID</dt><dd className="mt-1 truncate text-zinc-300">{item.submissionId||'—'}</dd></div><div><dt className="text-zinc-600">Form</dt><dd className="mt-1 truncate text-zinc-300">{item.formName||'—'}</dd></div><div><dt className="text-zinc-600">Company</dt><dd className="mt-1 truncate text-zinc-300">{item.company||'—'}</dd></div><div><dt className="text-zinc-600">Submitted IST</dt><dd className="mt-1 truncate text-zinc-300">{item.submittedAtIst||'—'}</dd></div></dl><p className="mt-3 line-clamp-2 text-xs leading-5 text-zinc-400">{item.message||item.deliveryNotes||'No message provided.'}</p><div className="mt-4 flex items-end justify-between gap-3 border-t border-white/5 pt-3"><div className="min-w-0 text-[9px] text-zinc-600"><span className="block">Created: {format(item.createdAt)}</span><span className="block">Changed: {format(item.updatedAt)}</span></div><div className="flex shrink-0 gap-1"><Icon label="Edit" onClick={()=>setEditing(item)}><Pencil size={14}/></Icon><Icon label="Delete" onClick={()=>remove(item)}><Trash2 size={14}/></Icon></div></div></article>)}</div>
  <div className="hidden overflow-hidden rounded-2xl border border-white/10 bg-[#151517] lg:block"><div className="overflow-x-auto"><table className="w-full min-w-[1280px] text-left text-[10px]"><thead className="uppercase tracking-wide text-zinc-500"><tr>{['Submission','Submitted','Type / form','Contact','Company','Source page','Quality','Created / last change','Actions'].map(head=><th key={head} className="px-3 py-3">{head}</th>)}</tr></thead><tbody>{rows.map(item=><tr key={item.id} className="border-t border-white/5 text-zinc-300"><td className="px-3 py-3 font-bold text-white">{item.submissionId||'—'}</td><td className="px-3 py-3"><b className="block">IST: {item.submittedAtIst||'—'}</b><small className="text-zinc-500">UTC: {item.submittedAtUtc||'—'}</small></td><td className="px-3 py-3"><b className="block">{item.submissionType||'—'}</b><small className="text-zinc-500">{item.formName||'—'}</small></td><td className="px-3 py-3"><b className="block">{item.fullName||'—'}</b><small className="block text-zinc-500">{item.email||item.phone||'—'}</small></td><td className="px-3 py-3">{item.company||'—'}</td><td className="max-w-48 truncate px-3 py-3">{item.sourcePage||'—'}</td><td className="px-3 py-3"><select aria-label={`Quality for ${item.fullName||item.submissionId}`} value={item.quality||'Neutral'} onChange={event=>quality(item,event.target.value)} className="h-8 rounded-lg border border-white/10 bg-[#101012] px-2 text-[10px] text-white outline-none"><option>Good</option><option>Neutral</option><option>Bad</option></select></td><td className="px-3 py-3"><b className="block text-white">Created: {format(item.createdAt)}</b><small className="text-zinc-500">Last change: {format(item.updatedAt)}</small></td><td className="px-3 py-3"><div className="flex gap-1"><Icon label="Edit" onClick={()=>setEditing(item)}><Pencil size={14}/></Icon><Icon label="Delete" onClick={()=>remove(item)}><Trash2 size={14}/></Icon></div></td></tr>)}</tbody></table></div></div>
  {!rows.length&&<div className="grid min-h-32 place-items-center rounded-2xl border border-white/10 bg-[#151517] text-xs text-zinc-600"><FileText size={22}/><span>No web form submissions to show.</span></div>}
  {editing!==undefined&&<SubmissionModal record={editing} close={()=>setEditing(undefined)} save={save}/>}
 </div>
}

function SubmissionModal({record,close,save}:{record:WebFormSubmission|null;close:()=>void;save:(value:WebFormSubmission)=>void}){const [form,setForm]=useState(record||blank());return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/80 p-2 sm:p-5"><div role="dialog" aria-modal="true" className="max-h-[96vh] w-full max-w-5xl overflow-auto rounded-2xl border border-white/15 bg-[#171719] p-4 sm:max-h-[90vh] sm:rounded-3xl sm:p-6"><header className="mb-4 flex items-center justify-between sm:mb-5"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#f16133]">Web Form</p><h2 className="font-display text-xl font-bold sm:text-2xl">{record?'Edit submission':'Add submission'}</h2></div><button aria-label="Close" onClick={close}><X/></button></header><form onSubmit={event=>{event.preventDefault();save(form)}} className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{columns.map(([key,label])=><Field key={key} label={label} value={form[key]} multiline={['message','deliveryNotes','userAgent'].includes(key)} set={value=>setForm(current=>({...current,[key]:value}))}/>) }<div className="sticky bottom-0 flex justify-end gap-2 border-t border-white/10 bg-[#171719] py-3 sm:col-span-2 lg:col-span-3"><button type="button" onClick={close} className="rounded-xl border border-white/10 px-4 py-2.5 text-xs">Cancel</button><button className="rounded-xl bg-[#f16133] px-5 py-2.5 text-xs font-bold">Save submission</button></div></form></div></div>}
function Field({label,value,set,multiline=false}:{label:string;value:string;set:(value:string)=>void;multiline?:boolean}){return <label className={`${multiline?'sm:col-span-2 lg:col-span-3':''} grid gap-1 text-[10px] font-bold text-zinc-400`}>{label}{multiline?<textarea rows={3} className={`${input} h-auto`} value={value} onChange={event=>set(event.target.value)}/>:<input className={input} value={value} onChange={event=>set(event.target.value)}/>}</label>}
function Icon({label,onClick,children}:{label:string;onClick:()=>void;children:React.ReactNode}){return <button aria-label={label} title={label} onClick={onClick} className="grid size-8 place-items-center rounded-lg border border-white/10 text-zinc-400 hover:text-[#f16133]">{children}</button>}
function Export({records}:{records:WebFormSubmission[]}){const run=()=>{if(!records.length)return;const quote=(value:string)=>`"${value.replaceAll('"','""')}"`;const csv='\uFEFF'+[[...columns.map(([,label])=>quote(label)),quote('Quality')].join(','),...records.map(record=>[...columns.map(([key])=>quote(record[key])),quote(record.quality||'Neutral')].join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const anchor=document.createElement('a');anchor.href=url;anchor.download=`crm-web-forms-${new Date().toISOString().slice(0,10)}.csv`;anchor.click();URL.revokeObjectURL(url)};return <button onClick={run} className="flex h-10 items-center gap-2 rounded-xl border border-white/10 px-3 text-xs font-bold text-zinc-300"><Download size={15}/> Export Excel</button>}
function Import({onImport}:{onImport:(rows:WebFormSubmission[])=>void}){return <label className="flex h-10 cursor-pointer items-center gap-2 rounded-xl border border-white/10 px-3 text-xs font-bold text-zinc-300"><Upload size={15}/> Import Excel<input type="file" accept=".csv,text/csv" className="sr-only" onChange={async event=>{const file=event.target.files?.[0];if(file)onImport(parseCsv(await file.text()));event.currentTarget.value=''}}/></label>}
function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);const read=(line:string)=>{const values:string[]=[];let value='',quoted=false;for(let index=0;index<line.length;index++){const char=line[index];if(char==='"'&&quoted&&line[index+1]==='"'){value+='"';index++}else if(char==='"')quoted=!quoted;else if(char===','&&!quoted){values.push(value);value=''}else value+=char}values.push(value);return values};const headers=read(lines.shift()||'');const keys=headers.map(header=>header.trim().toLowerCase()==='quality'?'quality':columns.find(([,label])=>label.toLowerCase()===header.trim().toLowerCase())?.[0]),hasQuality=keys.includes('quality');return lines.map(line=>{const stamp=new Date().toISOString(),values=read(line),record=blank();if(!hasQuality)record.quality=undefined;keys.forEach((key,index)=>{if(!key)return;const value=values[index]?.trim()||'';if(key==='quality')record.quality=['Good','Bad','Neutral'].includes(value)?value as WebFormSubmission['quality']:'Neutral';else record[key]=value});record.id=record.submissionId||crypto.randomUUID();record.createdAt=stamp;record.updatedAt=stamp;return record})}
const normalized=(value:string)=>value.trim().toLowerCase().replace(/\s+/g,' ');
function identity(item:WebFormSubmission){if(item.submissionId.trim())return `id:${normalized(item.submissionId)}`;return `form:${[item.submittedAtUtc,item.submittedAtIst,item.formName,item.fullName,item.email,item.phone,item.sourcePage].map(normalized).join('|')}`}
function merge(current:WebFormSubmission[],incoming:WebFormSubmission[]){const records=new Map(current.map(item=>[identity(item),item]));for(const imported of incoming){const key=identity(imported),existing=records.get(key);if(!existing){records.set(key,imported);continue}const next={...existing,quality:imported.quality||existing.quality||'Neutral'};for(const [field] of columns){if(imported[field].trim())next[field]=imported[field]}const changed=columns.some(([field])=>next[field]!==existing[field])||next.quality!==existing.quality;if(changed)records.set(key,{...next,id:existing.id,createdAt:existing.createdAt,updatedAt:new Date().toISOString()})}return [...records.values()]}
