'use client';

import { useEffect, useRef, useState } from 'react';
import { Bell, BriefcaseBusiness, CalendarClock, Check, ChevronRight, CircleDollarSign, CircleUserRound, Columns3, LayoutDashboard, Menu, Pencil, Plus, Search, Settings, Target, Trash2, UsersRound, X } from 'lucide-react';
import { crmLogoutAction } from './actions';
import { ProspectsSection, type Prospect } from './prospects';

type Page = 'Dashboard'|'Prospects'|'Leads'|'Pipeline'|'Follow-ups'|'Clients'|'Payments'|'Settings';
type Status = 'New'|'Contacted'|'Interested'|'Meeting'|'Proposal Sent'|'Follow-up'|'Negotiation'|'Won'|'Lost';
export type Lead = {id:string;name:string;company:string;phone:string;email:string;service:string;source:string;status:Status;priority:'Hot'|'Warm'|'Cold';followUp:string;time:string;assigned:string;value:number;notes:string};
type Client = {id:string;name:string;company:string;phone:string;services:string;start:string;value:number;payment:'Paid'|'Pending'|'Overdue';status:'Active'|'Inactive'|'Completed'};
type Payment = {id:string;client:string;service:string;amount:number;due:string;paid:string;status:'Paid'|'Pending'|'Overdue';method:string};

const statuses:Status[]=['New','Contacted','Interested','Meeting','Proposal Sent','Follow-up','Negotiation','Won','Lost'];
export const services=['Brand Strategy','Logo Designing','UI & UX','Packaging Designing','Graphic Designing','Web Development','WordPress Development','Shopify Development','App Development','Marketplace Management','Performance Marketing','Social Media Marketing','SEO','Email Marketing','WhatsApp Marketing','AI Automation','AI Agents','AI Sales Agent','Marketing Automation','Content Creation','Google My Business','Content Writing','CRM Development','AEO & GEO','Personal Branding'];
const sources=['Website','Google','Instagram','Facebook','Meta Ads','LinkedIn','WhatsApp','Referral','Cold Calling','Cold Email','Networking','Other'];
const today=new Date().toISOString().slice(0,10); const day=(n:number)=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)}; const money=(n:number)=>`₹${n.toLocaleString('en-IN')}`;
const seedLeads:Lead[]=[
 {id:'1',name:'Rahul Sharma',company:'Northstar Labs',phone:'+91 98765 43210',email:'rahul@example.com',service:'Web Development',source:'Website',status:'Contacted',priority:'Hot',followUp:today,time:'11:00',assigned:'Vaibhav',value:80000,notes:'Needs a conversion-focused company website.'},
 {id:'2',name:'Priya Mehta',company:'ABC Fashion',phone:'+91 98111 22000',email:'priya@example.com',service:'SEO',source:'Instagram',status:'Proposal Sent',priority:'Warm',followUp:today,time:'14:30',assigned:'Aarav',value:35000,notes:'Interested in a six-month SEO engagement.'},
 {id:'3',name:'Aman Verma',company:'XYZ Pvt Ltd',phone:'+91 99887 66554',email:'aman@example.com',service:'Social Media Marketing',source:'Referral',status:'Negotiation',priority:'Hot',followUp:day(1),time:'17:00',assigned:'Vaibhav',value:50000,notes:'Finalizing monthly deliverables.'},
 {id:'4',name:'Neha Singh',company:'Studio Nine',phone:'+91 91234 56789',email:'neha@example.com',service:'Brand Strategy',source:'LinkedIn',status:'New',priority:'Cold',followUp:day(-1),time:'12:00',assigned:'Aarav',value:25000,notes:'New identity enquiry.'},
];
const seedClients:Client[]=[{id:'1',name:'Riya Kapoor',company:'Kora Living',phone:'+91 90000 11111',services:'SEO, Social Media Marketing',start:'2026-08-01',value:60000,payment:'Pending',status:'Active'}];
const seedPayments:Payment[]=[{id:'1',client:'Kora Living',service:'SEO',amount:30000,due:day(-2),paid:'',status:'Overdue',method:'Bank Transfer'}];
const nav=[["Dashboard",LayoutDashboard],["Prospects",Target],["Leads",CircleUserRound],["Pipeline",Columns3],["Follow-ups",CalendarClock],["Clients",BriefcaseBusiness],["Payments",CircleDollarSign],["Settings",Settings]] as const;
const input='w-full rounded-xl border border-white/10 bg-[#101012] px-4 py-3 text-sm text-white outline-none focus:border-[#f16133]';
const card='rounded-2xl border border-white/10 bg-[#151517]';

export function CrmWorkspace(){
 const [page,setPage]=useState<Page>('Dashboard'),[leads,setLeads]=useState(seedLeads),[prospects,setProspects]=useState<Prospect[]>([]),[clients,setClients]=useState(seedClients),[payments,setPayments]=useState(seedPayments),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[edit,setEdit]=useState<Lead|null|undefined>(undefined),[mobile,setMobile]=useState(false),[ready,setReady]=useState(false),[syncState,setSyncState]=useState<'Loading'|'Saved'|'Saving'|'Offline'|'Conflict'>('Loading');
 const version=useRef(0), saveQueue=useRef(Promise.resolve());
 useEffect(()=>{let active=true;(async()=>{try{const response=await fetch('/api/crm/workspace',{cache:'no-store'});const remote=await response.json();if(!response.ok)throw new Error(remote.error||'Unable to load CRM data.');if(!active)return;let payload=remote.payload;setSyncState('Saved');version.current=remote.version||0;if(!payload){try{payload=JSON.parse(localStorage.getItem('dcampaign-crm')||'null')}catch{localStorage.removeItem('dcampaign-crm')}}if(payload){setLeads(payload.leads||[]);setProspects(payload.prospects||[]);setClients(payload.clients||[]);setPayments(payload.payments||[])}setReady(true)}catch(error){if(active){setSyncState('Offline');setReady(true);console.error(error)}}})();return()=>{active=false}},[]);
 useEffect(()=>{if(!ready)return;const timer=window.setTimeout(()=>{const payload={leads,prospects,clients,payments};setSyncState('Saving');saveQueue.current=saveQueue.current.then(async()=>{const response=await fetch('/api/crm/workspace',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({payload,version:version.current})});const result=await response.json();if(response.status===409){setSyncState('Conflict');return}if(!response.ok){setSyncState('Offline');return}version.current=result.version;localStorage.removeItem('dcampaign-crm');setSyncState('Saved')}).catch(()=>setSyncState('Offline'))},700);return()=>window.clearTimeout(timer)},[ready,leads,prospects,clients,payments]);
 const open=(p:Page)=>{setPage(p);setQuery('');setFilter('All');setMobile(false)}; const followups=leads.filter(l=>l.followUp&&!['Won','Lost'].includes(l.status));const prospectFollowups=prospects.filter(p=>p.nextOutreach&&p.status!=='Converted to Lead');const overdue=[...followups.filter(l=>l.followUp<today),...prospectFollowups.filter(p=>p.nextOutreach<today)];
 return <section className="mx-auto max-w-7xl px-6 pb-16 pt-28 md:px-12">
  <div className="mb-3 flex items-center justify-between lg:hidden"><button onClick={()=>setMobile(true)} className="flex items-center gap-2 rounded-lg border border-white/10 bg-[#151517] px-3 py-2 text-sm"><Menu size={18}/> Menu</button><b className="text-[10px] tracking-[.2em] text-[#f16133]">DCAMPAIGN CRM</b></div>
  <div className="grid gap-5 lg:grid-cols-[220px_minmax(0,1fr)]">
   {mobile&&<button aria-label="Close menu overlay" onClick={()=>setMobile(false)} className="fixed inset-0 z-[69] bg-black/70 lg:hidden"/>}
   <aside className={`${card} ${mobile?'fixed inset-y-0 left-0 z-[70] flex w-[260px]':'hidden'} h-[calc(100vh-132px)] min-h-[570px] flex-col p-4 lg:sticky lg:top-[104px] lg:flex`}>
    <div className="relative border-b border-white/10 px-2 pb-5 pt-2"><span className="text-[10px] font-extrabold tracking-[.2em] text-[#f16133]">DCAMPAIGN</span><strong className="mt-1 block font-display text-xl">Sales CRM</strong><button aria-label="Close menu" onClick={()=>setMobile(false)} className="absolute right-1 top-2 lg:hidden"><X/></button></div>
    <nav className="grid gap-1 py-4">{nav.map(([n,I])=><button key={n} onClick={()=>open(n)} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-bold ${page===n?'bg-[#f16133] text-white':'text-zinc-400 hover:bg-white/5 hover:text-white'}`}><I size={18}/>{n}{n==='Follow-ups'&&overdue.length>0&&<em className="ml-auto rounded-full bg-white px-2 py-0.5 text-[9px] not-italic text-black">{overdue.length}</em>}</button>)}</nav>
    <div className="mt-auto border-t border-white/10 px-2 pt-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-[#2a1711] text-xs font-bold text-[#ff8b60]">VD</span><div><b className="block text-xs">DCampaign Team</b><small className="text-[10px] text-zinc-500">CRM workspace</small></div></div><form action={crmLogoutAction}><button className="mt-3 w-full rounded-lg border border-white/10 px-3 py-2 text-left text-[10px] font-bold text-zinc-400 hover:border-brand/50 hover:text-white">Log out</button></form></div>
   </aside>
   <main className="min-w-0"><header className="mb-5 flex min-h-16 items-center justify-between"><div><p className="text-[10px] font-extrabold tracking-[.2em] text-[#f16133]">DCAMPAIGN DIGITAL CRM</p><h1 className="mt-1 font-display text-4xl font-extrabold tracking-tight">{page}</h1><span className={`mt-2 inline-flex text-[9px] font-bold ${syncState==='Saved'?'text-emerald-400':syncState==='Conflict'?'text-amber-300':'text-zinc-500'}`}>{syncState==='Saved'?'● Online · all changes saved':syncState==='Saving'?'● Saving online…':syncState==='Loading'?'● Loading workspace…':syncState==='Conflict'?'● Newer data exists · refresh required':'● Unable to sync · check connection'}</span></div><div className="flex gap-2"><button onClick={()=>open('Follow-ups')} aria-label="Follow-up alerts" className="relative grid size-11 place-items-center rounded-xl border border-white/10 bg-[#151517]"><Bell size={18}/>{overdue.length>0&&<i className="absolute -right-1 -top-1 grid size-5 place-items-center rounded-full border-2 border-black bg-[#f16133] text-[8px] not-italic">{overdue.length}</i>}</button><button onClick={()=>setEdit(null)} className="flex items-center gap-2 rounded-xl bg-[#f16133] px-4 py-3 text-xs font-extrabold hover:bg-[#d55328]"><Plus size={17}/> Add lead</button></div></header>
    {page==='Dashboard'&&<Dashboard {...{leads,clients,payments,due:followups.filter(l=>l.followUp===today),overdue:followups.filter(l=>l.followUp<today),open}} add={()=>setEdit(null)}/>} {page==='Prospects'&&<ProspectsSection {...{prospects,setProspects,leads,services}} addLead={lead=>setLeads(v=>[lead,...v])}/>} {page==='Leads'&&<Leads {...{leads,setLeads,query,setQuery,filter,setFilter}} edit={setEdit}/>} {page==='Pipeline'&&<Pipeline {...{leads,setLeads}}/>} {page==='Follow-ups'&&<Followups leads={followups} setLeads={setLeads} edit={setEdit} prospects={prospectFollowups} setProspects={setProspects}/>} {page==='Clients'&&<Clients {...{clients,setClients,query,setQuery}}/>} {page==='Payments'&&<Payments {...{payments,setPayments,clients}}/>} {page==='Settings'&&<SettingsPanel/>}
   </main>
  </div>{edit!==undefined&&<LeadModal lead={edit} close={()=>setEdit(undefined)} save={l=>{setLeads(v=>edit?v.map(x=>x.id===l.id?l:x):[l,...v]);setEdit(undefined)}}/>}
 </section>
}

function Dashboard({leads,clients,payments,due,overdue,open,add}:{leads:Lead[];clients:Client[];payments:Payment[];due:Lead[];overdue:Lead[];open:(p:Page)=>void;add:()=>void}){const metrics=[['Total Leads',leads.length],['New Leads',leads.filter(l=>l.status==='New').length],['Follow-ups Today',due.length],['Overdue Follow-ups',overdue.length],['Active Clients',clients.filter(c=>c.status==='Active').length],['Deals Won',leads.filter(l=>l.status==='Won').length],['Pending Payments',money(payments.filter(p=>p.status!=='Paid').reduce((a,p)=>a+p.amount,0))]];return <div className="grid gap-4"><div className="flex items-center justify-between rounded-2xl border border-[#f16133]/35 bg-[#21120e] p-4"><div><span className="flex items-center gap-2 text-[10px] font-extrabold tracking-[.16em] text-[#ff8b60]"><Bell size={15}/>WHAT NEEDS YOUR ATTENTION</span><b className="mt-2 block font-display">{due.length} due today · {overdue.length} overdue</b></div><button onClick={()=>open('Follow-ups')} className="flex items-center text-xs font-bold text-[#ff8b60]">Review <ChevronRight/></button></div><div className="grid grid-cols-2 gap-2 md:grid-cols-4">{metrics.map(([a,b])=><article key={a} className={`${card} p-4`}><span className="text-[10px] text-zinc-500">{a}</span><strong className="mt-2 block font-display text-2xl">{b}</strong></article>)}</div><div className="grid gap-4 md:grid-cols-[1.25fr_.75fr]"><Panel title="Today's follow-ups">{due.length?due.map(l=><div key={l.id} className="flex items-center gap-3 border-t border-white/5 py-3 first:border-0"><span className="grid size-9 place-items-center rounded-full bg-[#2a1711] text-xs font-bold text-[#ff8b60]">{l.name[0]}</span><div><b className="block text-xs">{l.name}</b><small className="text-[10px] text-zinc-500">{l.company} · {l.service}</small></div><time className="ml-auto text-xs font-bold text-[#ff8b60]">{l.time}</time></div>):<Empty text="Nothing due today."/>}</Panel><Panel title="Quick actions"><div className="grid gap-2"><Quick onClick={add} icon={<Plus/>} title="Add lead" sub="Capture a new enquiry"/><Quick onClick={()=>open('Follow-ups')} icon={<CalendarClock/>} title="Follow-ups" sub="Plan the next action"/><Quick onClick={()=>open('Clients')} icon={<UsersRound/>} title="Add client" sub="Manage client records"/></div></Panel></div><Panel title="Leads by status"><div className="grid gap-3 md:grid-cols-2">{statuses.slice(0,7).map(s=>{const n=leads.filter(l=>l.status===s).length;return <div key={s} className="grid grid-cols-[95px_1fr_20px] items-center gap-2 text-[10px] text-zinc-400"><span>{s}</span><i className="h-1.5 overflow-hidden rounded-full bg-white/10"><b className="block h-full rounded-full bg-[#f16133]" style={{width:`${Math.max(4,n/leads.length*100)}%`}}/></i><strong className="text-right text-white">{n}</strong></div>})}</div></Panel></div>}

function Leads({leads,setLeads,query,setQuery,filter,setFilter,edit}:{leads:Lead[];setLeads:React.Dispatch<React.SetStateAction<Lead[]>>;query:string;setQuery:(s:string)=>void;filter:string;setFilter:(s:string)=>void;edit:(l:Lead)=>void}){const rows=leads.filter(l=>(filter==='All'||l.status===filter||l.priority===filter)&&`${l.name} ${l.company} ${l.phone} ${l.service}`.toLowerCase().includes(query.toLowerCase()));return <div className="grid gap-4"><Toolbar {...{query,setQuery,filter,setFilter}}/><Table heads={['Lead','Service','Source','Status','Priority','Follow-up','Value','Actions']}>{rows.map(l=><tr key={l.id}><Cell main={l.name} sub={`${l.company} · ${l.phone}`}/><td>{l.service}</td><td>{l.source}</td><td><select value={l.status} onChange={e=>setLeads(v=>v.map(x=>x.id===l.id?{...x,status:e.target.value as Status}:x))} className="rounded-lg border border-white/10 bg-[#111] p-2 text-[10px]">{statuses.map(s=><option key={s}>{s}</option>)}</select></td><td><Badge v={l.priority}/></td><Cell main={l.followUp} sub={`${l.time} · ${l.assigned}`}/><td>{money(l.value)}</td><td><div className="flex gap-1"><IconButton label="Edit" onClick={()=>edit(l)}><Pencil size={15}/></IconButton><IconButton label="Delete" onClick={()=>setLeads(v=>v.filter(x=>x.id!==l.id))}><Trash2 size={15}/></IconButton></div></td></tr>)}</Table></div>}
function Pipeline({leads,setLeads}:{leads:Lead[];setLeads:React.Dispatch<React.SetStateAction<Lead[]>>}){return <div className="grid grid-flow-col auto-cols-[220px] gap-2 overflow-x-auto pb-4">{statuses.map(s=><section key={s} className={`${card} min-h-[520px] p-3`}><header className="mb-3 flex justify-between text-xs font-bold"><span>{s}</span><b className="rounded-full bg-white/10 px-2">{leads.filter(l=>l.status===s).length}</b></header>{leads.filter(l=>l.status===s).map(l=><article key={l.id} className="mb-2 rounded-xl border border-white/10 bg-[#1b1b1d] p-3"><Badge v={l.priority}/><h3 className="mt-3 font-display font-bold">{l.name}</h3><p className="mt-1 text-[10px] text-zinc-500">{l.company} · {l.service}</p><b className="mt-3 block text-xs text-[#ff8b60]">{money(l.value)}</b><small className="mt-2 block text-[9px] text-zinc-500">{l.followUp} · {l.time}</small><select value={l.status} onChange={e=>setLeads(v=>v.map(x=>x.id===l.id?{...x,status:e.target.value as Status}:x))} className="mt-3 w-full rounded-lg border border-white/10 bg-[#111] p-2 text-[9px]">{statuses.map(x=><option key={x}>{x}</option>)}</select></article>)}</section>)}</div>}
function Followups({leads,setLeads,edit,prospects,setProspects}:{leads:Lead[];setLeads:React.Dispatch<React.SetStateAction<Lead[]>>;edit:(l:Lead)=>void;prospects:Prospect[];setProspects:React.Dispatch<React.SetStateAction<Prospect[]>>}){const [tab,setTab]=useState('Today');const match=(date:string)=>tab==='Today'?date===today:tab==='Upcoming'?date>today:tab==='Overdue'?date<today:false;const rows=leads.filter(l=>match(l.followUp));const prospectRows=prospects.filter(p=>match(p.nextOutreach));return <div className="grid gap-4"><div className="flex border-b border-white/10">{['Today','Upcoming','Overdue','Completed'].map(t=><button onClick={()=>setTab(t)} key={t} className={`border-b-2 px-4 py-3 text-xs font-bold ${t===tab?'border-[#f16133] text-white':'border-transparent text-zinc-500'}`}>{t}</button>)}</div><div className={`${card} px-5`}>{rows.map(l=><article key={`lead-${l.id}`} className="grid gap-3 border-t border-white/5 py-4 first:border-0 md:grid-cols-[1fr_auto_auto] md:items-center"><div><div className="flex gap-2"><Badge v="Lead"/><Badge v={l.followUp<today?'Overdue':l.priority}/></div><h3 className="mt-2 font-display font-bold">{l.name}</h3><p className="text-[10px] text-zinc-500">{l.company} · {l.service} · {l.phone}</p></div><time className="text-xs text-[#ff8b60]">{l.followUp} · <b>{l.time}</b></time><div className="flex gap-2"><button onClick={()=>setLeads(v=>v.map(x=>x.id===l.id?{...x,status:'Contacted',followUp:''}:x))} className="flex items-center gap-1 rounded-lg bg-[#f16133] px-3 py-2 text-[10px] font-bold"><Check size={14}/> Complete</button><button onClick={()=>edit(l)} className="rounded-lg border border-white/10 px-3 py-2 text-[10px] font-bold">Reschedule</button></div></article>)}{prospectRows.map(p=><article key={`prospect-${p.id}`} className="grid gap-3 border-t border-white/5 py-4 first:border-0 md:grid-cols-[1fr_auto_auto] md:items-center"><div><div className="flex gap-2"><Badge v="Prospect"/><Badge v={p.nextOutreach<today?'Overdue':p.priority}/></div><h3 className="mt-2 font-display font-bold">{p.businessName}</h3><p className="text-[10px] text-zinc-500">{p.contactPerson||'No contact person'} · {p.nextMethod} · {p.phone||'No phone'}</p></div><time className="text-xs text-[#ff8b60]">{p.nextOutreach} · <b>{p.nextTime}</b></time><button onClick={()=>setProspects(v=>v.map(x=>x.id===p.id?{...x,nextOutreach:'',nextTime:''}:x))} className="flex items-center gap-1 rounded-lg bg-[#f16133] px-3 py-2 text-[10px] font-bold"><Check size={14}/> Complete</button></article>)}{!rows.length&&!prospectRows.length&&<Empty text={`No ${tab.toLowerCase()} follow-ups.`}/>}</div></div>}

function Clients({clients,setClients,query,setQuery}:{clients:Client[];setClients:React.Dispatch<React.SetStateAction<Client[]>>;query:string;setQuery:(s:string)=>void}){const [show,setShow]=useState(false);const rows=clients.filter(c=>`${c.name} ${c.company} ${c.services}`.toLowerCase().includes(query.toLowerCase()));return <div className="grid gap-4"><div className="flex gap-2"><SearchBox value={query} set={setQuery} placeholder="Search clients or services"/><button onClick={()=>setShow(true)} className="rounded-xl bg-[#f16133] px-4 text-xs font-bold">Add client</button></div><Table heads={['Client','Services','Start date','Value','Payment','Status']}>{rows.map(c=><tr key={c.id}><Cell main={c.name} sub={`${c.company} · ${c.phone}`}/><td>{c.services}</td><td>{c.start}</td><td>{money(c.value)}</td><td><Badge v={c.payment}/></td><td><Badge v={c.status}/></td></tr>)}</Table>{show&&<SimpleModal title="Add client" close={()=>setShow(false)} fields={['Contact person','Company','Phone','Service','Client value']} selects={{Service:services}} save={v=>{setClients(x=>[{id:crypto.randomUUID(),name:v['Contact person'],company:v.Company,phone:v.Phone,services:v.Service,start:today,value:Number(v['Client value']),payment:'Pending',status:'Active'},...x]);setShow(false)}}/>}</div>}
function Payments({payments,setPayments,clients}:{payments:Payment[];setPayments:React.Dispatch<React.SetStateAction<Payment[]>>;clients:Client[]}){const [show,setShow]=useState(false);return <div className="grid gap-4"><div className="flex items-center gap-3"><article className={`${card} p-4`}><small className="text-zinc-500">Receivable</small><b className="mt-1 block font-display text-xl">{money(payments.filter(p=>p.status!=='Paid').reduce((a,p)=>a+p.amount,0))}</b></article><button onClick={()=>setShow(true)} className="ml-auto rounded-xl bg-[#f16133] px-4 py-3 text-xs font-bold">Add payment</button></div><Table heads={['Client','Service','Amount','Due','Paid date','Status','Method','Action']}>{payments.map(p=><tr key={p.id}><td>{p.client}</td><td>{p.service}</td><td>{money(p.amount)}</td><td>{p.due}</td><td>{p.paid||'—'}</td><td><Badge v={p.status}/></td><td>{p.method}</td><td>{p.status!=='Paid'&&<button onClick={()=>setPayments(v=>v.map(x=>x.id===p.id?{...x,status:'Paid',paid:today}:x))} className="text-[10px] font-bold text-[#ff8b60]">Mark paid</button>}</td></tr>)}</Table>{show&&<SimpleModal title="Add payment" close={()=>setShow(false)} fields={['Client','Service','Amount','Due date','Method']} selects={{Client:clients.map(c=>c.company),Service:services,Method:['UPI','Bank Transfer','Cash','Cheque','Other']}} save={v=>{setPayments(x=>[{id:crypto.randomUUID(),client:v.Client,service:v.Service,amount:Number(v.Amount),due:v['Due date']||day(7),paid:'',status:'Pending',method:v.Method},...x]);setShow(false)}}/>}</div>}
function SettingsPanel(){const [list,setList]=useState(services),[value,setValue]=useState('');return <div className="grid gap-4 md:grid-cols-2"><Panel title="Services"><div className="flex gap-2"><input className={input} value={value} onChange={e=>setValue(e.target.value)} placeholder="Add service"/><button onClick={()=>{if(value.trim()){setList(x=>[...x,value.trim()]);setValue('')}}} className="rounded-xl bg-[#f16133] px-4"><Plus/></button></div><div className="mt-4 flex flex-wrap gap-2">{list.map(s=><span key={s} className="flex items-center gap-1 rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-[9px] text-zinc-300">{s}<button onClick={()=>setList(x=>x.filter(a=>a!==s))}><X size={12}/></button></span>)}</div></Panel><div className="grid gap-4"><Panel title="Lead sources"><div className="flex flex-wrap gap-2">{sources.map(s=><Badge key={s} v={s}/>)}</div></Panel><Panel title="Team"><div className="grid gap-3 text-xs"><p><b>Vaibhav</b><small className="ml-2 text-zinc-500">Admin · Active</small></p><p><b>Aarav Kumar</b><small className="ml-2 text-zinc-500">Team Member · Active</small></p></div></Panel></div></div>}

function LeadModal({lead,close,save}:{lead:Lead|null;close:()=>void;save:(l:Lead)=>void}){const [f,setF]=useState<Lead>(lead||{id:crypto.randomUUID(),name:'',company:'',phone:'',email:'',service:services[0],source:'Website',status:'New',priority:'Warm',followUp:day(1),time:'11:00',assigned:'Vaibhav',value:0,notes:''});const set=(k:keyof Lead,v:string|number)=>setF(x=>({...x,[k]:v}));return <Modal title={lead?'Edit lead':'Add a new lead'} close={close}><form onSubmit={e=>{e.preventDefault();save(f)}} className="grid gap-3 md:grid-cols-2"><Field label="Lead name" value={f.name} set={v=>set('name',v)} required/><Field label="Company" value={f.company} set={v=>set('company',v)}/><Field label="Phone" value={f.phone} set={v=>set('phone',v)} required/><Field label="Email" value={f.email} set={v=>set('email',v)} type="email"/><Select label="Interested service" value={f.service} set={v=>set('service',v)} options={services}/><Select label="Lead source" value={f.source} set={v=>set('source',v)} options={sources}/><Select label="Status" value={f.status} set={v=>set('status',v)} options={statuses}/><Select label="Priority" value={f.priority} set={v=>set('priority',v)} options={['Hot','Warm','Cold']}/><Field label="Expected deal value" value={String(f.value)} set={v=>set('value',Number(v))} type="number"/><Field label="Assigned to" value={f.assigned} set={v=>set('assigned',v)}/><Field label="Next follow-up" value={f.followUp} set={v=>set('followUp',v)} type="date"/><Field label="Time" value={f.time} set={v=>set('time',v)} type="time"/><label className="grid gap-1 text-[10px] font-bold text-zinc-400 md:col-span-2">Requirement / notes<textarea className={input} rows={3} value={f.notes} onChange={e=>set('notes',e.target.value)}/></label><div className="flex justify-end gap-2 md:col-span-2"><button type="button" onClick={close} className="rounded-xl border border-white/10 px-4 py-3 text-xs font-bold">Cancel</button><button className="rounded-xl bg-[#f16133] px-5 py-3 text-xs font-bold">Save lead</button></div></form></Modal>}
function SimpleModal({title,close,fields,selects,save}:{title:string;close:()=>void;fields:string[];selects:Record<string,string[]>;save:(v:Record<string,string>)=>void}){const [v,setV]=useState<Record<string,string>>(()=>Object.fromEntries(fields.map(f=>[f,selects[f]?.[0]||''])));return <Modal title={title} close={close}><form onSubmit={e=>{e.preventDefault();save(v)}} className="grid gap-3 md:grid-cols-2">{fields.map(f=>selects[f]?<Select key={f} label={f} value={v[f]} set={x=>setV(a=>({...a,[f]:x}))} options={selects[f]}/>:<Field key={f} label={f} value={v[f]} set={x=>setV(a=>({...a,[f]:x}))} type={f.includes('date')?'date':f.includes('value')||f==='Amount'?'number':'text'}/>)}<div className="flex justify-end gap-2 md:col-span-2"><button type="button" onClick={close} className="rounded-xl border border-white/10 px-4 py-3 text-xs">Cancel</button><button className="rounded-xl bg-[#f16133] px-5 py-3 text-xs font-bold">Save</button></div></form></Modal>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[100] grid place-items-center bg-black/80 p-5"><div role="dialog" aria-modal="true" className="max-h-[88vh] w-full max-w-3xl overflow-auto rounded-3xl border border-white/15 bg-[#171719] p-6 shadow-2xl"><header className="mb-5 flex items-start justify-between"><div><p className="text-[9px] font-bold tracking-[.2em] text-[#f16133]">CRM RECORD</p><h2 className="font-display text-3xl font-bold">{title}</h2></div><button aria-label="Close" onClick={close} className="rounded-lg border border-white/10 p-2"><X/></button></header>{children}</div></div>}
function Toolbar({query,setQuery,filter,setFilter}:{query:string;setQuery:(s:string)=>void;filter:string;setFilter:(s:string)=>void}){return <div className="flex flex-col gap-2 sm:flex-row"><SearchBox value={query} set={setQuery} placeholder="Search leads, company, phone or service"/><select value={filter} onChange={e=>setFilter(e.target.value)} className={`${input} sm:w-44`}><option>All</option>{statuses.map(s=><option key={s}>{s}</option>)}{['Hot','Warm','Cold'].map(s=><option key={s}>{s}</option>)}</select></div>}
function SearchBox({value,set,placeholder}:{value:string;set:(s:string)=>void;placeholder:string}){return <label className="flex flex-1 items-center gap-2 rounded-xl border border-white/10 bg-[#151517] px-3"><Search size={17} className="text-zinc-500"/><input value={value} onChange={e=>set(e.target.value)} placeholder={placeholder} className="w-full bg-transparent py-3 text-sm outline-none"/></label>}
function Table({heads,children}:{heads:string[];children:React.ReactNode}){return <div className={`${card} overflow-auto`}><table className="w-full min-w-[800px] border-collapse text-left"><thead><tr>{heads.map(h=><th key={h} className="p-3 text-[9px] uppercase tracking-wider text-zinc-500">{h}</th>)}</tr></thead><tbody className="text-[11px] text-zinc-300 [&_td]:border-t [&_td]:border-white/5 [&_td]:p-3">{children}</tbody></table></div>}
function Cell({main,sub}:{main:string;sub:string}){return <td><b className="block text-xs text-white">{main}</b><small className="mt-1 block text-[9px] text-zinc-500">{sub}</small></td>}
function Badge({v}:{v:string}){const tone=['Hot','Overdue','Lost'].includes(v)?'border-[#f16133]/40 bg-[#31160f] text-[#ff8b60]':['Paid','Active','Won'].includes(v)?'border-emerald-700/40 bg-emerald-950/50 text-emerald-300':'border-white/10 bg-white/5 text-zinc-300';return <span className={`inline-flex rounded-full border px-2 py-1 text-[9px] font-bold ${tone}`}>{v}</span>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <section className={`${card} p-5`}><h2 className="mb-4 font-display text-lg font-bold">{title}</h2>{children}</section>}
function Quick({onClick,icon,title,sub}:{onClick:()=>void;icon:React.ReactNode;title:string;sub:string}){return <button onClick={onClick} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.025] p-3 text-left text-[#f16133] [&_svg]:size-5"><span>{icon}</span><span><b className="block text-xs text-white">{title}</b><small className="text-[9px] text-zinc-500">{sub}</small></span></button>}
function IconButton({label,onClick,children}:{label:string;onClick:()=>void;children:React.ReactNode}){return <button aria-label={label} onClick={onClick} className="rounded-lg border border-white/10 p-2 text-zinc-400 hover:text-[#f16133]">{children}</button>}
function Empty({text}:{text:string}){return <div className="grid min-h-28 place-items-center content-center gap-2 text-zinc-600"><CalendarClock size={22}/><p className="text-xs">{text}</p></div>}
function Field({label,value,set,type='text',required=false}:{label:string;value:string;set:(s:string)=>void;type?:string;required?:boolean}){return <label className="grid gap-1 text-[10px] font-bold text-zinc-400">{label}<input className={input} required={required} type={type} value={value} onChange={e=>set(e.target.value)}/></label>}
function Select({label,value,set,options}:{label:string;value:string;set:(s:string)=>void;options:readonly string[]}){return <label className="grid gap-1 text-[10px] font-bold text-zinc-400">{label}<select className={input} value={value} onChange={e=>set(e.target.value)}>{options.map(o=><option key={o}>{o}</option>)}</select></label>}
