-- Development/demo data only. Run after migrations 001–004 in a non-production Supabase project.
do $$
declare demo_client uuid; seo uuid; meta uuid; social uuid; web uuid; demo_project uuid;
begin
  select id into demo_client from public.clients where slug='acme-fashion-demo';
  if demo_client is null then insert into public.clients(company_name,slug,status,industry,package_name,contact_name,contact_email) values ('Acme Fashion Pvt Ltd','acme-fashion-demo','active','Fashion & Lifestyle','Growth Partner','Demo Client','demo@example.com') returning id into demo_client; end if;
  select id into seo from public.services where slug='seo'; select id into meta from public.services where slug='meta-ads'; select id into social from public.services where slug='social-media'; select id into web from public.services where slug='website-development';
  insert into public.client_services(client_id,service_id,progress,status) values (demo_client,seo,72,'active'),(demo_client,meta,84,'active'),(demo_client,social,60,'active'),(demo_client,web,72,'active') on conflict do nothing;
  insert into public.projects(client_id,service_id,title,description,status,progress,priority) values (demo_client,seo,'Organic growth programme','Technical SEO, content, and authority work for the next reporting period.','active',72,'high'),(demo_client,web,'Commerce experience refresh','Design and development improvements for a faster shopping journey.','active',58,'medium');
  select id into demo_project from public.projects where client_id=demo_client and title='Commerce experience refresh' order by created_at desc limit 1;
  insert into public.project_milestones(project_id,title,status,progress,display_order) values (demo_project,'Discovery','completed',100,1),(demo_project,'Design','completed',100,2),(demo_project,'Development','in_progress',65,3),(demo_project,'Testing','not_started',0,4),(demo_project,'Launch','not_started',0,5);
  insert into public.tasks(client_id,project_id,service_id,title,status,priority,visible_to_client) values (demo_client,demo_project,web,'Homepage design approved','completed','high',true),(demo_client,demo_project,web,'Responsive development','in_progress','high',true),(demo_client,demo_project,web,'QA and browser testing','planned','medium',true);
  insert into public.seo_snapshots(client_id,period_start,period_end,organic_users,organic_clicks,impressions,conversions,backlinks,referring_domains) values (demo_client,current_date-30,current_date,18420,6240,182000,184,420,138) on conflict do nothing;
  insert into public.seo_keywords(client_id,keyword,current_position,previous_position,target_url,status) values (demo_client,'best digital marketing agency',3,6,'/','improving'),(demo_client,'performance marketing agency',8,11,'/services','improving'),(demo_client,'seo agency india',12,10,'/services/seo','watch');
  insert into public.marketing_performance(client_id,platform,period_start,period_end,spend,revenue,roas,purchases,ctr,cpc,cpa) values (demo_client,'meta',current_date-30,current_date,86240,412680,4.78,96,2.74,18.60,898) on conflict do nothing;
  insert into public.marketing_performance(client_id,platform,period_start,period_end,spend,revenue,roas,conversions,ctr,cpc,cpa) values (demo_client,'google',current_date-30,current_date,54800,228400,4.16,142,3.12,24.10,386) on conflict do nothing;
  insert into public.social_performance(client_id,platform,period_start,period_end,followers,follower_change,reach,engagement_rate,posts_published,reels_published) values (demo_client,'instagram',current_date-30,current_date,24680,1240,482000,8.2,12,10) on conflict do nothing;
  insert into public.activities(client_id,activity_type,title,description,visible_to_client) values (demo_client,'task_completed','Homepage design approved','Your web team completed a milestone.',true),(demo_client,'report_uploaded','Monthly performance report uploaded','Your latest report is ready to review.',true),(demo_client,'campaign_updated','Meta campaign optimised','Performance settings were refined.',true);
end $$;
