'use server';
import { revalidatePath } from 'next/cache';
import { z } from 'zod';
import { requireCurrentClientContext } from '@/lib/queries/client-context';
const profileSchema = z.object({ fullName: z.string().trim().min(2).max(120), phone: z.string().trim().max(30).optional() });
export async function updateProfileAction(formData: FormData) { const parsed = profileSchema.safeParse({ fullName: formData.get('fullName'), phone: formData.get('phone') }); if (!parsed.success) throw new Error(parsed.error.issues[0]?.message ?? 'Invalid profile'); const { supabase } = await requireCurrentClientContext(); const { error } = await supabase!.rpc('update_own_profile', { new_full_name: parsed.data.fullName, new_phone: parsed.data.phone || null, new_avatar_url: null }); if (error) throw new Error('Profile could not be updated'); revalidatePath('/client/settings'); revalidatePath('/client/dashboard'); }
export async function updatePreferencesAction(formData: FormData) { const { supabase, profile } = await requireCurrentClientContext(); const { error } = await supabase!.from('notification_preferences').upsert({ profile_id: profile!.id, email_notifications: formData.get('emailNotifications') === 'on', portal_notifications: formData.get('portalNotifications') === 'on', updated_at: new Date().toISOString() }, { onConflict: 'profile_id' }); if (error) throw new Error('Preferences could not be updated'); revalidatePath('/client/settings'); }
const passwordSchema = z.object({ password: z.string().min(10).max(128), confirmation: z.string() }).refine((value) => value.password === value.confirmation, { message: 'Passwords do not match', path: ['confirmation'] });
export async function changePasswordAction(formData: FormData) { const parsed = passwordSchema.safeParse({ password: formData.get('password'), confirmation: formData.get('confirmation') }); if (!parsed.success) throw new Error(parsed.error.issues[0]?.message ?? 'Invalid password'); const { supabase } = await requireCurrentClientContext(); const { error } = await supabase!.auth.updateUser({ password: parsed.data.password }); if (error) throw new Error('Password could not be updated'); }
