import { NextResponse } from 'next/server';
import { z } from 'zod';
import { createSupabaseAdminClient } from '@/lib/supabase/admin';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { isCrmRole } from '@/lib/auth/permissions';

const notificationInput=z.object({title:z.string().trim().min(1).max(120),message:z.string().trim().min(1).max(1000)});

async function context(){const auth=await createSupabaseServerClient();if(!auth)return null;const {data:{user}}=await auth.auth.getUser();if(!user)return null;const admin=createSupabaseAdminClient();const {data:profile}=await admin.from('profiles').select('id,role,is_active,full_name').eq('user_id',user.id).maybeSingle();return profile?.is_active&&isCrmRole(profile.role)?{admin,profile}:null}

export async function POST(request:Request){const ctx=await context();if(!ctx)return NextResponse.json({error:'Unauthorized'},{status:401});const parsed=notificationInput.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Add a title and notification message.'},{status:400});const {data:state,error}=await ctx.admin.from('crm_workspace_state').select('payload,version').eq('id','primary').maybeSingle();if(error||!state)return NextResponse.json({error:'CRM workspace is not ready.'},{status:503});const item={id:crypto.randomUUID(),...parsed.data,createdAt:new Date().toISOString(),createdBy:ctx.profile.full_name||'CRM user',isActive:true};const source=state.payload as Record<string,unknown>;const payload={...source,notifications:[item,...((source.notifications as object[])||[])].slice(0,2000)};const {data,error:updateError}=await ctx.admin.from('crm_workspace_state').update({payload,version:state.version+1,updated_by:ctx.profile.id,updated_at:new Date().toISOString()}).eq('id','primary').eq('version',state.version).select('version,payload').maybeSingle();if(updateError||!data)return NextResponse.json({error:'Workspace changed. Please try again.'},{status:409});return NextResponse.json(data)}

export async function DELETE(request:Request){const ctx=await context();if(!ctx)return NextResponse.json({error:'Unauthorized'},{status:401});const id=new URL(request.url).searchParams.get('id');if(!id)return NextResponse.json({error:'Notification is required.'},{status:400});const {data:state}=await ctx.admin.from('crm_workspace_state').select('payload,version').eq('id','primary').maybeSingle();if(!state)return NextResponse.json({error:'CRM workspace is not ready.'},{status:503});const source=state.payload as Record<string,unknown>;const notifications=((source.notifications as {id:string}[])||[]).filter(item=>item.id!==id);const {data,error}=await ctx.admin.from('crm_workspace_state').update({payload:{...source,notifications},version:state.version+1,updated_by:ctx.profile.id,updated_at:new Date().toISOString()}).eq('id','primary').eq('version',state.version).select('version,payload').maybeSingle();if(error||!data)return NextResponse.json({error:'Workspace changed. Please try again.'},{status:409});return NextResponse.json(data)}
