import { ApprovalResponseForm } from './approval-response-form';
import { OperationsShell, EmptyOperation } from '@/components/portal/operations-shell';
import { getCurrentClientContext } from '@/lib/queries/client-context';

export default async function ApprovalsPage() {
  const { supabase, clientId } = await getCurrentClientContext();
  const approvals = supabase && clientId ? (await supabase.from('approvals').select('id,title,description,status,due_date,created_at,preview_url,client_response,responded_at').eq('client_id', clientId).order('created_at', { ascending: false })).data ?? [] : [];
  return <OperationsShell kicker="Approvals" title="Work waiting for your voice." description="Review requests from your team and keep campaigns moving with a clear, recorded response.">{approvals.length === 0 ? <EmptyOperation>There are no approval requests waiting for you.</EmptyOperation> : <div className="mt-8 space-y-4">{approvals.map((item) => <article key={item.id} className="glass-card rounded-2xl p-6 md:p-7"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-sm font-bold uppercase tracking-widest text-brand">Approval request</p><h2 className="mt-2 font-display text-xl font-extrabold">{item.title}</h2></div><span className="h-fit rounded-full border border-brand/25 bg-brand/10 px-3 py-1.5 text-xs font-bold uppercase tracking-wider text-brand-light">{String(item.status).replaceAll('_', ' ')}</span></div>{item.description && <p className="mt-4 max-w-3xl text-base leading-7 text-white/55">{item.description}</p>}<div className="mt-5 flex flex-wrap gap-6 text-sm text-white/45"><span>Requested {new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium' }).format(new Date(item.created_at))}</span>{item.due_date && <span>Due {item.due_date}</span>}{item.preview_url && <a href={item.preview_url} target="_blank" rel="noreferrer" className="font-bold text-brand-light hover:text-white">Open preview ↗</a>}</div>{item.status === 'pending' ? <ApprovalResponseForm approvalId={item.id} title={item.title} /> : item.client_response && <div className="mt-5 rounded-xl border border-white/8 bg-white/[0.03] p-4"><p className="text-xs font-extrabold uppercase tracking-wider text-white/35">Your response</p><p className="mt-2 text-sm leading-6 text-white/70">{item.client_response}</p></div>}</article>)}</div>}</OperationsShell>;
}
