import Link from 'next/link';
import { notFound } from 'next/navigation';
import { createSupabaseServerClient } from '@/lib/supabase/server';
import { createResourceAction } from './actions';

const titles: Record<string, string> = { projects: 'Project', tasks: 'Task', services: 'Service', reports: 'Report', approvals: 'Approval', invoices: 'Invoice', support: 'Support ticket', files: 'File', team: 'Team member' };
const input = 'mt-2 h-12 w-full rounded-xl border border-white/10 bg-white/[0.04] px-4 text-sm outline-none focus:border-brand';

export default async function NewResourcePage({ params }: { params: Promise<{ resource: string }> }) {
  const { resource } = await params; if (!titles[resource]) notFound();
  const supabase = await createSupabaseServerClient();
  const clients = supabase ? ((await supabase.from('clients').select('id,company_name').order('company_name')).data ?? []) : [];
  if (resource === 'files' || resource === 'team') return <section className="max-w-2xl"><Link href={`/admin/${resource}`} className="text-sm font-bold text-brand-light">← Back</Link><div className="mt-8 rounded-3xl border border-white/8 bg-white/[0.025] p-8"><p className="text-sm font-extrabold uppercase tracking-widest text-brand">{titles[resource]} workflow</p><h1 className="mt-3 font-display text-3xl font-extrabold">Use the dedicated workflow</h1><p className="mt-3 text-white/50">This section requires secure file upload or an authentication invitation and will be added to its own frontend workflow.</p></div></section>;
  return <section className="max-w-2xl"><Link href={`/admin/${resource}`} className="text-sm font-bold text-brand-light">← Back to {resource}</Link><div className="mt-8 rounded-3xl border border-white/8 bg-white/[0.025] p-7 sm:p-9"><p className="text-sm font-extrabold uppercase tracking-widest text-brand">Admin workspace</p><h1 className="mt-3 font-display text-3xl font-extrabold">Add {titles[resource]}</h1><form action={createResourceAction} className="mt-8 space-y-5"><input type="hidden" name="resource" value={resource} />{resource === 'services' ? <><label className="block text-sm font-bold">Name<input name="name" required className={input} /></label><label className="block text-sm font-bold">Slug<input name="slug" required className={input} placeholder="social-media" /></label><label className="block text-sm font-bold">Description<textarea name="description" className={`${input} h-28 py-3`} /></label></> : resource === 'invoices' ? <><label className="block text-sm font-bold">Invoice number<input name="invoice_number" required className={input} /></label><ClientSelect clients={clients} /><label className="block text-sm font-bold">Total (INR)<input name="total" type="number" min="0" step="0.01" required className={input} /></label><label className="block text-sm font-bold">Due date<input name="due_date" type="date" className={input} /></label></> : <><label className="block text-sm font-bold">{resource === 'support' ? 'Subject' : 'Title'}<input name={resource === 'support' ? 'subject' : 'title'} required className={input} /></label><ClientSelect clients={clients} />{resource === 'reports' && <label className="block text-sm font-bold">Report type<input name="report_type" required className={input} placeholder="monthly" /></label>}{resource === 'support' && <label className="block text-sm font-bold">Category<input name="category" className={input} placeholder="general" /></label>}{(resource === 'projects' || resource === 'tasks') && <label className="block text-sm font-bold">Description<textarea name="description" className={`${input} h-28 py-3`} /></label>}{resource === 'approvals' && <label className="block text-sm font-bold">Description<textarea name="description" className={`${input} h-28 py-3`} /></label>}</>}<button className="min-h-12 rounded-xl bg-brand px-6 text-sm font-extrabold hover:bg-brand-dark">Create {titles[resource]}</button></form></div></section>;
}

function ClientSelect({ clients }: { clients: Array<{ id: string; company_name: string }> }) { return <label className="block text-sm font-bold">Client<select name="client_id" required className={input}><option value="">Select client</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.company_name}</option>)}</select></label>; }
