'use client';

import Link from 'next/link';
import { useState } from 'react';
import type { ReactNode } from 'react';
import { PortalHeader } from '../components/portal-header';
import { LoginForm } from './client/login/login-form';

const highlights = [
  ['01', 'Performance', 'Live campaign progress across every connected service.'],
  ['02', 'Approvals', 'Review, comment, and keep decisions moving.'],
  ['03', 'Workspace', 'Reports, files, invoices, and support in one place.'],
] as const;

const faqs = [
  ['What will I see inside my portal?', 'Active services, progress, campaign metrics, reports, files, approvals, invoices, and support.'],
  ['Is my company information private?', 'Yes. Each client receives a secure workspace with permission-based access.'],
  ['Can more than one team member get access?', 'Yes. Your DCampaign account manager can invite additional users.'],
] as const;

export default function Home() {
  const [openFaq, setOpenFaq] = useState(0);
  const [loginMode, setLoginMode] = useState<'client' | 'employee'>('client');
  return <main className="min-h-screen bg-white text-zinc-950">
    <PortalHeader />
    <section id="login" className="relative flex min-h-[58vh] items-center overflow-hidden bg-[#080808] py-20 text-white md:min-h-[62vh] md:py-24 lg:py-28">
      <div className="hero-ambient-gradient pointer-events-none absolute inset-0" /><div className="hero-grid pointer-events-none absolute inset-0 opacity-20" /><div className="pointer-events-none absolute -left-20 top-0 size-96 rounded-full bg-[#f16133]/15 blur-[130px]" />
      <div className="relative z-10 mx-auto grid w-full max-w-7xl gap-12 px-6 md:grid-cols-[1.05fr_.95fr] md:items-center md:px-12"><div className="max-w-3xl"><p className="text-xs font-extrabold uppercase tracking-[.2em] text-[#f16133]">DCAMPAIGN CLIENT GROWTH PORTAL</p><h1 className="mt-5 font-display text-4xl font-extrabold leading-[1.08] tracking-tight sm:text-5xl md:text-6xl">Every campaign. Every result. <span className="creative-underline text-[#f16133]">One workspace.</span></h1><p className="mt-6 max-w-2xl text-base leading-7 text-zinc-300 md:text-lg">Your private command centre for performance, delivery, approvals, and collaboration with the DCampaign team.</p><div className="mt-8 flex flex-wrap gap-4"><a href="#features" className="rounded border border-white/25 px-7 py-3.5 text-xs font-bold uppercase tracking-wider transition hover:border-[#f16133] hover:text-[#f16133]">Explore features</a></div></div><div className="rounded-3xl border border-white/10 bg-[#151518]/95 p-6 shadow-2xl shadow-black/40 backdrop-blur-xl sm:p-8"><div className="mb-6 flex rounded-xl border border-white/10 bg-white/[.03] p-1"><button type="button" onClick={() => setLoginMode('client')} className={`flex-1 rounded-lg px-3 py-2.5 text-xs font-bold uppercase tracking-wider transition ${loginMode === 'client' ? 'bg-[#f16133] text-white' : 'text-white/45 hover:text-white'}`}>Client login</button><button type="button" onClick={() => setLoginMode('employee')} className={`flex-1 rounded-lg px-3 py-2.5 text-xs font-bold uppercase tracking-wider transition ${loginMode === 'employee' ? 'bg-[#f16133] text-white' : 'text-white/45 hover:text-white'}`}>Employee login</button></div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-[#f16133]">{loginMode === 'client' ? 'Client workspace' : 'Team workspace'}</p><h2 className="mt-2 font-display text-2xl font-extrabold">Sign in to continue.</h2><p className="mt-2 mb-6 text-sm leading-6 text-white/45">{loginMode === 'client' ? 'Access your campaigns, reports, approvals, and files.' : 'Access internal delivery, client workspaces, and operations.'}</p><LoginForm /></div></div>
    </section>
    <section id="features" className="border-b border-zinc-200 bg-white py-10"><div className="mx-auto grid max-w-7xl gap-4 px-6 md:grid-cols-3 md:px-12">{highlights.map(([n, title, copy]) => <article key={title} className="group rounded-2xl border border-zinc-200 bg-zinc-50/60 p-5 transition duration-300 hover:-translate-y-1 hover:border-[#f16133]/40 hover:bg-white hover:shadow-lg"><div className="flex gap-4"><span className="font-display text-sm font-black tracking-widest text-[#f16133]">{n}</span><div><h2 className="font-display text-lg font-extrabold">{title}</h2><p className="mt-2 text-sm leading-6 text-zinc-600">{copy}</p></div></div></article>)}</div></section>
    <section className="bg-[#f2f3f5] py-16 md:py-20"><div className="mx-auto grid max-w-7xl gap-10 px-6 md:grid-cols-[.8fr_1.2fr] md:items-center md:px-12"><div><p className="text-xs font-bold uppercase tracking-widest text-[#f16133]">YOUR WORKSPACE, AT A GLANCE</p><h2 className="mt-3 font-display text-3xl font-extrabold leading-tight md:text-4xl">Clear progress. Faster decisions.</h2><p className="mt-4 max-w-md text-sm leading-7 text-zinc-600">Replace scattered updates with one calm view of what is moving, what needs attention, and what comes next.</p><a href="#login" className="mt-6 inline-flex rounded bg-[#f16133] px-6 py-3 text-xs font-bold uppercase tracking-widest text-white hover:bg-[#d55328]">View your workspace</a></div><DashboardPreview /></div></section>
    <section id="faq" className="bg-white py-16 md:py-20"><div className="mx-auto grid max-w-5xl gap-10 px-6 md:grid-cols-[.8fr_1.2fr] md:px-12"><div><p className="text-xs font-bold uppercase tracking-widest text-[#f16133]">QUICK ANSWERS</p><h2 className="mt-3 font-display text-3xl font-extrabold leading-tight">Everything you need before signing in.</h2></div><div className="space-y-3">{faqs.map(([q, a], i) => { const open = openFaq === i; return <div key={q} className="overflow-hidden rounded-xl border border-zinc-200"><button type="button" onClick={() => setOpenFaq(open ? -1 : i)} className="flex w-full items-center justify-between gap-4 px-5 py-4 text-left font-display text-sm font-bold hover:text-[#f16133]"><span>{q}</span><span className={`text-xl text-[#f16133] transition-transform ${open ? 'rotate-45' : ''}`}>+</span></button><div className={`grid transition-all duration-300 ${open ? 'grid-rows-[1fr] border-t border-zinc-100' : 'grid-rows-[0fr]'}`}><div className="overflow-hidden"><p className="bg-zinc-50/60 px-5 py-4 text-sm leading-6 text-zinc-600">{a}</p></div></div></div>; })}</div></div></section>
    <section className="relative overflow-hidden bg-[#0b0b0c] py-14 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_80%_50%,rgba(241,97,51,.18),transparent_40%)]" /><div className="relative mx-auto flex max-w-7xl flex-col justify-between gap-6 px-6 md:flex-row md:items-center md:px-12"><div><p className="text-xs font-bold uppercase tracking-widest text-[#f16133]">READY WHEN YOU ARE</p><h2 className="mt-2 font-display text-2xl font-extrabold md:text-3xl">Everything important. One login away.</h2></div><a href="#login" className="shrink-0 rounded bg-[#f16133] px-7 py-3.5 text-xs font-bold uppercase tracking-widest hover:bg-[#d55328]">Sign in</a></div></section>
    <footer className="border-t border-zinc-900 bg-[#080808] py-6 text-zinc-500"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 px-6 text-xs md:flex-row md:px-12"><p>© 2026 DCampaign Digital. All rights reserved.</p><div className="flex gap-5"><a href="mailto:contact@dcampaign.com" className="hover:text-[#f16133]">contact@dcampaign.com</a><a href="#login" className="hover:text-[#f16133]">Client login</a></div></div></footer>
  </main>;
}

function DashboardPreview() { return <div className="rounded-2xl border border-white/10 bg-[#151518] p-4 text-white shadow-2xl md:p-5"><div className="flex justify-between border-b border-white/10 pb-4"><div><p className="text-xs font-bold">ABC Company</p><p className="mt-1 text-[.6rem] uppercase tracking-wider text-zinc-500">September overview</p></div><span className="rounded-full bg-emerald-400/10 px-2.5 py-1 text-[.6rem] font-bold uppercase text-emerald-300">On track</span></div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{[['SEO', '72%'], ['Meta Ads', '84%'], ['Social', '60%'], ['Website', '92%']].map(([label, value]) => <div key={label} className="rounded-lg border border-white/8 bg-white/[.035] p-3"><p className="text-[.55rem] font-bold uppercase tracking-wider text-zinc-500">{label}</p><p className="mt-2 font-display text-lg font-extrabold">{value}</p><div className="mt-2 h-1 rounded bg-white/10"><div className="h-full rounded bg-[#f16133]" style={{ width: value }} /></div></div>)}</div><div className="mt-3 rounded-lg border border-white/8 bg-white/[.025] p-4"><p className="text-[.6rem] font-bold uppercase tracking-widest text-[#f16133]">Recent activity</p>{['Meta campaign optimised', 'SEO report published'].map((item, index) => <div key={item} className="flex items-center gap-3 border-b border-white/8 py-2.5 text-xs text-zinc-300 last:border-0"><span className="grid size-5 place-items-center rounded-full bg-[#f16133]/15 text-[#f16133]">{index + 1}</span>{item}</div>)}</div></div>; }
