import { EmptyReport, Kpi, ReportShell } from '@/components/reporting/report-shell';
import { requireCurrentServiceContext } from '@/lib/queries/client-context';

export default async function ClientSeoPage() {
  const { supabase, clientId } = await requireCurrentServiceContext('seo');
  const [snapshotResult, keywordResult] = await Promise.all([
    supabase!.from('seo_snapshots').select('*').eq('client_id', clientId).order('period_end', { ascending: false }).limit(1).maybeSingle(),
    supabase!.from('seo_keywords').select('keyword,current_position,previous_position,target_url,status').eq('client_id', clientId).order('current_position', { ascending: true }).limit(50),
  ]);
  const snapshot = snapshotResult.data;
  const keywords = keywordResult.data ?? [];
  return <ReportShell kicker="SEO performance" title="Search visibility, made clear." description="Track organic traffic, search demand, keyword movement, and the SEO work moving your account forward.">{snapshot ? <><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Kpi label="Organic traffic" value={(snapshot.organic_users ?? 0).toLocaleString('en-IN')} /><Kpi label="Organic clicks" value={(snapshot.organic_clicks ?? 0).toLocaleString('en-IN')} /><Kpi label="Impressions" value={(snapshot.impressions ?? 0).toLocaleString('en-IN')} /><Kpi label="Conversions" value={(snapshot.conversions ?? 0).toLocaleString('en-IN')} /></div><section className="glass-card mt-8 rounded-2xl p-6"><p className="text-sm font-extrabold uppercase tracking-widest text-brand">Keyword positions</p><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="text-xs uppercase tracking-widest text-white/40"><tr><th className="pb-3">Keyword</th><th className="pb-3">Current</th><th className="pb-3">Previous</th><th className="pb-3">Change</th><th className="pb-3">Target page</th></tr></thead><tbody className="divide-y divide-white/8">{keywords.map((row) => { const change = row.previous_position && row.current_position ? row.previous_position - row.current_position : 0; return <tr key={row.keyword}><td className="py-4 font-semibold">{row.keyword}</td><td className="py-4">{row.current_position ?? '—'}</td><td className="py-4 text-white/45">{row.previous_position ?? '—'}</td><td className={`py-4 font-bold ${change > 0 ? 'text-emerald-300' : change < 0 ? 'text-red-300' : 'text-white/40'}`}>{change > 0 ? `↑ ${change}` : change < 0 ? `↓ ${Math.abs(change)}` : '—'}</td><td className="max-w-56 truncate py-4 text-white/45">{row.target_url ?? '—'}</td></tr>; })}</tbody></table></div></section></> : <EmptyReport />}</ReportShell>;
}
