import Link from 'next/link';
import { EmptyOperation, OperationsShell } from '@/components/portal/operations-shell';
import { requireCurrentServiceContext } from '@/lib/queries/client-context';

export default async function WebsiteDevelopmentPage() {
  const { supabase, clientId } = await requireCurrentServiceContext('website-development');
  const projects = supabase && clientId ? (await supabase.from('projects').select('id,title,description,status,progress,due_date,project_milestones(id,title,status,progress,due_date,display_order)').eq('client_id', clientId).order('updated_at', { ascending: false })).data ?? [] : [];
  return <OperationsShell kicker="Website development" title="Your website, milestone by milestone." description="Follow discovery, design, development, testing, and launch from a single delivery view.">{projects.length === 0 ? <EmptyOperation>Your website project will appear here when the delivery plan is ready.</EmptyOperation> : <div className="mt-8 space-y-6">{projects.map((project) => <article key={project.id} className="glass-card rounded-3xl p-6 md:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-sm font-extrabold uppercase tracking-widest text-brand">{String(project.status).replaceAll('_', ' ')}</p><h2 className="mt-2 font-display text-2xl font-extrabold">{project.title}</h2>{project.description && <p className="mt-3 max-w-3xl text-base leading-7 text-white/50">{project.description}</p>}</div><p className="font-display text-2xl font-extrabold">{project.progress}%</p></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-brand" style={{ width: `${project.progress}%` }} /></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{(project.project_milestones ?? []).sort((a, b) => a.display_order - b.display_order).map((milestone) => <div key={milestone.id} className="rounded-xl border border-white/8 p-4"><p className="text-sm font-bold">{milestone.title}</p><p className="mt-2 text-xs capitalize text-white/40">{String(milestone.status).replaceAll('_', ' ')}</p></div>)}</div><Link href={`/client/projects/${project.id}`} className="mt-6 inline-flex min-h-11 items-center text-sm font-bold text-brand-light">Open project details →</Link></article>)}</div>}</OperationsShell>;
}
