import Image from 'next/image';
import Link from 'next/link';
import type { ReactNode } from 'react';
import { logoutAction } from '@/app/auth/actions';
import { BarChart3, BriefcaseBusiness, CheckSquare, ChevronDown, CircleHelp, FileText, FolderKanban, LayoutDashboard, LifeBuoy, Receipt, Settings, Users } from 'lucide-react';

const navigation = [
  ['Overview', '/admin/dashboard', LayoutDashboard], ['Clients', '/admin/clients', Users], ['Projects', '/admin/projects', FolderKanban], ['Tasks', '/admin/tasks', CheckSquare],
  ['Services', '/admin/services', BriefcaseBusiness], ['Reports', '/admin/reports', BarChart3], ['Files', '/admin/files', FileText], ['Approvals', '/admin/approvals', CheckSquare],
  ['Invoices', '/admin/invoices', Receipt], ['Support', '/admin/support', LifeBuoy], ['Team', '/admin/team', Users],
] as const;

function Nav() { return <nav aria-label="Admin workspace" className="space-y-1">{navigation.map(([label, href, Icon]) => <Link key={href} href={href} className="group flex min-h-11 items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold text-white/55 transition hover:bg-white/6 hover:text-white"><Icon size={17} strokeWidth={1.8} className="text-white/35 transition group-hover:text-brand" />{label}</Link>)}</nav>; }

export function AdminShell({ children, adminName }: { children: ReactNode; adminName: string }) {
  return <main className="min-h-screen bg-[#09090a] text-white"><header className="sticky top-0 z-40 border-b border-white/8 bg-[#0d0d0f]/90 backdrop-blur-xl"><div className="mx-auto flex h-[76px] max-w-[1600px] items-center justify-between px-5 sm:px-8"><Link href="/admin/dashboard" className="flex items-center gap-4"><Image src="/dcampaign-logo-white.webp" alt="DCampaign" width={167} height={32} priority className="h-7 w-auto" /><span className="hidden h-7 border-l border-white/15 pl-4 text-xs font-extrabold uppercase tracking-[0.22em] text-white/45 md:block">Admin portal</span></Link><div className="flex items-center gap-3"><div className="hidden items-center gap-2 rounded-xl border border-white/10 bg-white/[0.035] px-3 py-2 sm:flex"><span className="grid h-7 w-7 place-items-center rounded-lg bg-brand/15 text-xs font-extrabold text-brand">{adminName.slice(0,1).toUpperCase()}</span><div><p className="text-xs font-bold leading-4">{adminName}</p><p className="text-[10px] uppercase tracking-widest text-white/35">Administrator</p></div><ChevronDown size={15} className="ml-2 text-white/35" /></div><form action={logoutAction}><button className="min-h-10 rounded-xl border border-brand/60 px-4 text-xs font-extrabold uppercase tracking-wider text-brand-light transition hover:bg-brand hover:text-white">Sign out</button></form></div></div><details className="border-t border-white/8 lg:hidden"><summary className="cursor-pointer list-none px-5 py-3 text-sm font-bold text-brand-light">Open admin menu</summary><div className="border-t border-white/8 bg-[#101012] p-4"><Nav /></div></details></header><div className="mx-auto grid max-w-[1600px] lg:grid-cols-[260px_minmax(0,1fr)]"><aside className="sticky top-[76px] hidden h-[calc(100vh-4.75rem)] overflow-y-auto border-r border-white/8 px-5 py-8 lg:block"><div className="mb-7 rounded-2xl border border-brand/20 bg-brand/8 p-4"><p className="text-[10px] font-extrabold uppercase tracking-[0.2em] text-brand">Workspace</p><p className="mt-2 text-sm font-bold">DCampaign operations</p><p className="mt-1 text-xs text-white/40">Manage delivery in one place</p></div><p className="mb-4 px-3 text-[10px] font-extrabold uppercase tracking-[0.2em] text-white/30">Main menu</p><Nav /><div className="mt-8 border-t border-white/8 pt-5"><Link href="/admin/settings" className="flex items-center gap-3 px-3 py-2.5 text-sm font-semibold text-white/45 hover:text-white"><Settings size={17} />Settings</Link><Link href="mailto:contact@dcampaign.com" className="flex items-center gap-3 px-3 py-2.5 text-sm font-semibold text-white/45 hover:text-white"><CircleHelp size={17} />Help center</Link></div></aside><section className="min-w-0 px-5 py-8 sm:px-8 lg:px-10 lg:py-10">{children}</section></div></main>;
}
