'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import dynamic from 'next/dynamic';
import { Bell, BriefcaseBusiness, CalendarClock, CheckCircle2, FileText, FolderOpen, LayoutDashboard, LogOut, MessageSquare, Plus, Receipt, UserRound } from 'lucide-react';
import { canRespond, type PortalData, type PortalRecord, type Kind } from '@/lib/client-portal/schema';
import { leaveClientPortal } from '@/app/client-portal/actions';
import { Badge, button, card, External, field, Input, Modal, stamp, Text } from './primitives';
import type { Mutate } from './record-form';
const RecordForm=dynamic(()=>import('./record-form'));
const tabs=[['Dashboard',LayoutDashboard],['My Work',BriefcaseBusiness],['Deliverables',CheckCircle2],['Requests',MessageSquare],['Files',FolderOpen],['Meetings',CalendarClock],['Payments',Receipt],['Profile',UserRound]] as const;
type Tab=typeof tabs[number][0]|'Updates'|'Access';
const tabKinds:Partial<Record<Tab,Kind>>={'My Work':'work',Deliverables:'deliverable',Requests:'request',Files:'file',Meetings:'meeting'};
const money=(v:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(v);

export function ClientWorkspace({employee=false,initialClientId}:{employee?:boolean;initialClientId?:string}){
 const [data,setData]=useState<PortalData|null>(null),[accountId,setAccountId]=useState(''),[tab,setTab]=useState<Tab>(initialClientId?'Access':'Dashboard');
 const [error,setError]=useState(''),[loading,setLoading]=useState(true),[editing,setEditing]=useState<{kind:Kind;record?:PortalRecord}|null>(null),[selected,setSelected]=useState<string|null>(null),[logout,setLogout]=useState(false);
 const requestSequence=useRef(0);
 const refresh=useCallback(async()=>{
   const sequence=++requestSequence.current;
   const response=await fetch('/api/client-portal'+(accountId?'?account='+encodeURIComponent(accountId):''),{cache:'no-store'});
   const result=await response.json();
   if(sequence!==requestSequence.current)return;
   if(!response.ok){if(response.status===401||response.status===403)setData(null);throw new Error(result.error||'Unable to load your workspace.');}
   setData(result);setError('');
 },[accountId]);
 useEffect(()=>{let active=true;const load=()=>refresh().catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});void load();const timer=setInterval(load,10000);return()=>{active=false;clearInterval(timer);};},[refresh]);
 const mutate:Mutate=async(action,input)=>{
   const response=await fetch('/api/client-portal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,accountId:data?.account?.id,input})});
   const result=await response.json();if(!response.ok)throw new Error(result.error||'Unable to save.');
   if(result.accountId&&result.accountId!==accountId){setAccountId(result.accountId);}else await refresh();
 };
 if(loading&&!data)return <div className="p-10 text-zinc-400" role="status">Loading your workspace…</div>;
 if(!data)return <div className={`${card} mx-auto my-8 max-w-xl`}><h1 className="font-display text-2xl font-bold">Your client workspace</h1><p role="alert" className="mt-4 text-zinc-400">{error||'Your account manager is preparing access.'}</p><button className={`${button} mt-4`} onClick={()=>{setLoading(true);void refresh().catch(e=>setError(e.message)).finally(()=>setLoading(false));}}>Try again</button><form action={leaveClientPortal} className="mt-3"><button className={button}>Back to sign in</button></form></div>;
 const unread=data.events.filter(e=>!data.lastRead||e.created_at>data.lastRead);
 const kind=tabKinds[tab],record=data.records.find(r=>r.id===selected);
 const changeAccount=(id:string)=>{setData(null);setLoading(true);setSelected(null);setAccountId(id);};
 return <div className={employee?'min-w-0':'mx-auto max-w-[1600px] px-4 py-6 sm:px-8 lg:px-14'}>
  {employee&&<div className="mb-4 flex flex-wrap items-end gap-3"><label className="grid min-w-56 flex-1 gap-1 text-xs text-zinc-400">Client workspace<select className={field} value={data.account?.id||''} onChange={e=>changeAccount(e.target.value)}><option value="" disabled>Select a client</option>{data.accounts.map(a=><option key={a.id} value={a.id}>{a.company}{a.is_active?'':' (Disabled)'}</option>)}</select></label>{data.canInvite&&<button className={button} onClick={()=>setTab('Access')}><UserRound size={16}/> Portal access</button>}</div>}
  <div className={employee?'min-w-0':'grid min-w-0 gap-6 lg:grid-cols-[210px_minmax(0,1fr)]'}>
   <aside className={employee?'mb-5':'lg:sticky lg:top-24 lg:self-start'}><nav aria-label="Client portal" className={employee?'flex flex-wrap gap-2':'flex gap-2 overflow-x-auto rounded-2xl border border-white/10 bg-[#151517] p-3 lg:flex-col'}>{tabs.map(([name,Icon])=><button key={name} onClick={()=>setTab(name)} className={`flex min-h-11 shrink-0 items-center gap-3 rounded-xl px-3 text-sm font-bold ${tab===name?'bg-brand text-white':'text-zinc-400 hover:bg-white/5'}`}><Icon size={17}/>{name}</button>)}</nav>{!employee&&<button className={`${button} mt-4 w-full text-zinc-400`} onClick={()=>setLogout(true)}><LogOut size={16}/> Log out</button>}</aside>
   <section className="min-w-0"><header className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-brand">DCampaign · Client workspace</p><h1 className="mt-2 break-words font-display text-3xl font-bold">{tab==='Dashboard'?`Welcome, ${data.account?.company||'team'}`:tab}</h1><p className="mt-2 text-xs text-zinc-500">{employee?'Manage delivery and client collaboration.':'Your progress, feedback and next steps in one place.'}</p></div><button aria-label={`Updates, ${unread.length} unread`} className={`${button} relative`} onClick={()=>setTab('Updates')}><Bell size={18}/>{unread.length>0&&<span className="rounded-full bg-brand px-2 py-0.5 text-xs">{unread.length}</span>}</button></header>
    {error&&<p role="alert" className="mb-4 rounded-xl border border-red-400/20 p-3 text-sm text-red-300">{error}</p>}
    {tab==='Access'&&data.canInvite?<Access data={data} mutate={mutate} initialClientId={initialClientId}/>:!data.account?<div className={card}>No client workspaces are assigned yet.{data.canInvite&&<button className={`${button} ml-3`} onClick={()=>setTab('Access')}>Create portal access</button>}</div>:<>
     {tab==='Dashboard'&&<Dashboard data={data} open={setTab} select={setSelected}/>}
     {kind&&<><div className="mb-4 flex flex-wrap justify-between gap-3"><p className="text-sm text-zinc-500">{data.records.filter(r=>r.kind===kind).length} {tab.toLowerCase()} items</p>{(data.canManage||kind==='request'&&!employee)&&<button className={`${button} bg-brand`} onClick={()=>setEditing({kind})}><Plus size={16}/> {kind==='request'?'New request':`Add ${kind}`}</button>}</div><div className="grid gap-4 xl:grid-cols-2">{data.records.filter(r=>r.kind===kind).map(r=><RecordCard key={r.id} record={r} open={()=>setSelected(r.id)} employee={employee}/>)}{!data.records.some(r=>r.kind===kind)&&<Empty text={kind==='request'?'Submit a request and track its progress here.':'Your team will share updates here when they are ready.'}/>}</div></>}
     {tab==='Payments'&&<Payments data={data}/>}
     {tab==='Profile'&&<Profile data={data} mutate={mutate}/>}
     {tab==='Updates'&&<div className="space-y-3">{!employee&&<button className={button} onClick={()=>void mutate('read',{}).catch(e=>setError(e.message))}>Mark updates read</button>}{data.events.map(e=><button key={e.id} onClick={()=>setSelected(e.record_id)} className={`${card} block w-full text-left`}><div className="flex flex-wrap justify-between gap-2"><b>{e.kind} · {data.records.find(r=>r.id===e.record_id)?.details.title}</b><span className="text-xs text-zinc-500">{stamp(e.created_at)}</span></div><p className="mt-2 whitespace-pre-wrap text-sm text-zinc-400">{e.message}</p><p className="mt-2 text-xs text-zinc-500">{e.actor_name} · {e.actor_type}{!e.visible?' · Internal only':''}</p></button>)}{!data.events.length&&<Empty text="You’re up to date. New activity will appear here."/>}</div>}
    </>}
   </section>
  </div>
  {editing&&<RecordForm kind={editing.kind} record={editing.record} data={data} save={mutate} close={()=>setEditing(null)}/>}
  {record&&!editing&&<RecordDetail record={record} data={data} mutate={mutate} close={()=>setSelected(null)} edit={()=>setEditing({kind:record.kind,record})}/>}
  {logout&&<Modal title="Log out of your portal?" close={()=>setLogout(false)}><p className="text-zinc-400">You can sign back in whenever you need.</p><form action={leaveClientPortal} className="mt-5 flex justify-end gap-3"><button type="button" className={button} onClick={()=>setLogout(false)}>Stay signed in</button><button className={`${button} bg-brand`}>Log out</button></form></Modal>}
 </div>;
}

function Empty({text}:{text:string}){return <div className={`${card} col-span-full border-dashed py-10 text-center text-sm text-zinc-500`}><FileText className="mx-auto mb-3 text-brand" size={24}/>{text}</div>;}
function RecordCard({record:r,open,employee}:{record:PortalRecord;open:()=>void;employee:boolean}){return <article className={card}><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><p className="text-[10px] uppercase tracking-wider text-brand">{r.details.service||r.kind}{employee&&!r.visible?' · Internal':''}</p><h2 className="mt-2 break-words font-display text-xl font-bold">{r.details.title}</h2></div><Badge>{r.details.status}</Badge></div>{r.kind==='work'&&<div className="mt-5"><div className="mb-2 flex justify-between text-xs text-zinc-400"><span>Progress</span><span>{r.details.progress}%</span></div><progress aria-label={`${r.details.title} progress`} value={r.details.progress} max={100} className="h-2 w-full overflow-hidden rounded-full accent-[#f16133]"/></div>}<p className="mt-4 line-clamp-3 whitespace-pre-wrap text-sm leading-6 text-zinc-400">{r.details.latestUpdate||r.details.description||'Updates will appear here.'}</p><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-white/5 pt-4"><span className="text-xs text-zinc-500">{r.details.due?`${r.kind==='meeting'?'Meeting':'Due'}: ${r.details.due} ${r.details.time}${r.kind==='meeting'?' IST':''}`:`Updated ${stamp(r.updated_at)}`}</span><button className={button} onClick={open}>View details</button></div></article>;}
function Dashboard({data,open,select}:{data:PortalData;open:(t:Tab)=>void;select:(id:string)=>void}){
 const [now,setNow]=useState(()=>Date.now());
 useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),60000);return()=>clearInterval(timer);},[]);
 const work=data.records.filter(r=>r.kind==='work'&&!['Completed','On Hold'].includes(r.details.status));
 const approvals=data.records.filter(canRespond),requests=data.records.filter(r=>r.kind==='request'&&!['Completed','Rejected / Not Applicable'].includes(r.details.status));
 const meeting=data.records.filter(r=>r.kind==='meeting'&&r.details.status==='Scheduled'&&new Date(`${r.details.due}T${r.details.time||'00:00'}:00+05:30`).getTime()>=now).sort((a,b)=>(a.details.due+a.details.time).localeCompare(b.details.due+b.details.time))[0];
 const pending=data.payments.filter(p=>p.status!=='Cancelled').reduce((n,p)=>n+Math.max(0,p.amount-p.paidAmount),0);
 return <div className="space-y-5"><div className="grid grid-cols-2 gap-3 xl:grid-cols-4">{[['Active services',data.services.filter(s=>!['Completed','Cancelled','Inactive'].includes(s.status)).length],['Work in progress',work.length],['Pending approvals',approvals.length],['Open requests',requests.length]].map(([label,value])=><div className={card} key={label}><p className="text-xs text-zinc-400">{label}</p><strong className="mt-3 block font-display text-3xl">{value}</strong></div>)}</div>
  {approvals.length>0&&<div className="rounded-2xl border border-brand/30 bg-brand/5 p-5"><h2 className="font-display text-xl font-bold">Requires your attention</h2><div className="mt-3 flex flex-wrap gap-2">{approvals.map(r=><button key={r.id} className={button} onClick={()=>select(r.id)}>{r.details.title} →</button>)}</div></div>}
  <div className="grid gap-5 xl:grid-cols-2"><div className={card}><h2 className="mb-4 font-display text-xl font-bold">Current work</h2>{work.slice(0,5).map(r=><button key={r.id} className="block w-full border-t border-white/5 py-3 text-left" onClick={()=>select(r.id)}><span className="flex justify-between gap-3 text-sm"><b>{r.details.title}</b><span className="text-brand-light">{r.details.progress}%</span></span><p className="mt-1 text-xs text-zinc-500">{r.details.status}</p></button>)}{!work.length&&<p className="text-sm text-zinc-500">No active work yet.</p>}<button className={`${button} mt-3`} onClick={()=>open('My Work')}>View all work</button></div><div className="space-y-4"><div className={card}><h2 className="font-display text-xl font-bold">Next meeting</h2>{meeting?<><p className="mt-2">{meeting.details.title}</p><p className="my-3 text-sm text-zinc-400">{meeting.details.due} · {meeting.details.time} IST</p><External url={meeting.details.url} label="Join meeting"/></>:<p className="mt-3 text-sm text-zinc-500">No upcoming meetings.</p>}</div><div className={card}><h2 className="font-display text-xl font-bold">Payments</h2><p className="mt-2 text-2xl font-bold text-brand-light">{money(pending)}</p><p className="mt-1 text-xs text-zinc-500">Outstanding balance</p><button className={`${button} mt-3`} onClick={()=>open('Payments')}>View payments</button></div></div></div>
  <div className={card}><h2 className="font-display text-xl font-bold">Recent updates</h2>{data.events.slice(0,5).map(e=><button key={e.id} className="block w-full border-b border-white/5 py-3 text-left last:border-0" onClick={()=>select(e.record_id)}><p className="text-sm">{e.kind}: {e.message||data.records.find(r=>r.id===e.record_id)?.details.title}</p><p className="mt-1 text-xs text-zinc-500">{e.actor_name} · {stamp(e.created_at)}</p></button>)}{!data.events.length&&<p className="mt-3 text-sm text-zinc-500">Your team’s updates will appear here.</p>}</div>
 </div>;
}

function RecordDetail({record:r,data,mutate,close,edit}:{record:PortalRecord;data:PortalData;mutate:Mutate;close:()=>void;edit:()=>void}){
 const [message,setMessage]=useState(''),[attachment,setAttachment]=useState(''),[visible,setVisible]=useState(true),[pending,setPending]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false);
 const respond=async(action:string)=>{setPending(true);setError('');try{await mutate(action,{id:r.id,version:r.version,message,attachment,visible});setMessage('');setAttachment('');setConfirm(false);}catch(e){setError(e instanceof Error?e.message:'Unable to save.');}finally{setPending(false);}};
 return <Modal title={r.details.title} close={close}><div className="space-y-5"><div className="flex flex-wrap gap-2"><Badge>{r.details.status}</Badge>{!r.visible&&<Badge>Internal only</Badge>}{data.canManage&&<button className={button} onClick={edit}>Edit details</button>}</div><p className="whitespace-pre-wrap text-sm leading-7 text-zinc-300">{r.details.description}</p><div className="grid gap-3 text-xs text-zinc-400 sm:grid-cols-2"><span>Service: {r.details.service||'—'}</span><span>Created: {stamp(r.created_at)}</span><span>Start: {r.details.start||'—'}</span><span>Due: {r.details.due||'—'} {r.details.time}{r.kind==='meeting'?' IST':''}</span>{r.kind==='work'&&<span>Progress: {r.details.progress}%</span>}<span>Updated: {stamp(r.updated_at)}</span></div>{r.details.latestUpdate&&<div className="rounded-xl bg-brand/5 p-4 text-sm">{r.details.latestUpdate}</div>}{r.details.notes&&<p className="whitespace-pre-wrap text-sm text-zinc-400">{r.details.notes}</p>}<External url={r.details.url} label={r.kind==='meeting'?'Join meeting':'Open file / link'}/>
 <section><h3 className="mb-3 font-display text-lg font-bold">History & discussion</h3><div className="space-y-3">{data.events.filter(e=>e.record_id===r.id).map(e=><article key={e.id} className="rounded-xl border border-white/10 p-3"><div className="flex flex-wrap justify-between gap-2 text-xs"><b>{e.actor_name} · {e.actor_type}</b><span className="text-zinc-500">{stamp(e.created_at)}</span></div><p className="mt-2 text-xs text-brand-light">{e.kind}{!e.visible?' · Internal note':''}{e.snapshot&&r.kind==='work'?` · ${e.snapshot.progress}%`:''}</p><p className="mt-2 whitespace-pre-wrap break-words text-sm text-zinc-300">{e.message}</p><External url={e.attachment}/></article>)}</div></section>
 {['work','deliverable','request'].includes(r.kind)&&<form className="grid gap-3 border-t border-white/10 pt-4" onSubmit={e=>{e.preventDefault();void respond('comment');}}><Text label="Comment / feedback" value={message} onChange={setMessage}/><Input label="Optional attachment link (HTTPS)" value={attachment} onChange={setAttachment} type="url"/>{data.employee&&<label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={visible} onChange={e=>setVisible(e.target.checked)}/> Client-visible comment</label>}<div className="flex flex-wrap gap-2"><button disabled={pending||message.trim().length<2} className={button}>Post comment</button>{!data.employee&&canRespond(r)&&<><button type="button" disabled={pending} className={`${button} bg-brand`} onClick={()=>setConfirm(true)}>Approve</button><button type="button" disabled={pending||message.trim().length<2} className={button} onClick={()=>void respond('changes')}>Request changes</button></>}</div>{confirm&&<div className="rounded-xl border border-brand/40 p-4"><p className="text-sm">Are you sure you want to approve this deliverable?</p><div className="mt-3 flex gap-2"><button type="button" className={button} onClick={()=>setConfirm(false)}>Cancel</button><button type="button" disabled={pending} className={`${button} bg-brand`} onClick={()=>void respond('approve')}>Confirm approval</button></div></div>}</form>}{error&&<p role="alert" className="text-sm text-red-300">{error}</p>}
 </div></Modal>;
}

function Payments({data}:{data:PortalData}){const valid=data.payments.filter(p=>p.status!=='Cancelled');return <div className="space-y-4"><div className="grid grid-cols-2 gap-3"><div className={card}><p className="text-xs text-zinc-400">Received</p><b className="mt-2 block text-2xl">{money(valid.reduce((n,p)=>n+p.paidAmount,0))}</b></div><div className={card}><p className="text-xs text-zinc-400">Pending</p><b className="mt-2 block text-2xl text-brand-light">{money(valid.reduce((n,p)=>n+Math.max(0,p.amount-p.paidAmount),0))}</b></div></div>{data.payments.map(p=><article className={card} key={p.id}><div className="flex flex-wrap justify-between gap-2"><h2 className="font-bold">{p.service}</h2><Badge>{p.status==='Pending'&&p.due&&p.due<new Date().toISOString().slice(0,10)?'Overdue':p.status}</Badge></div><div className="mt-4 grid gap-3 text-sm sm:grid-cols-3"><span>Total: {money(p.amount)}</span><span>Paid: {money(p.paidAmount)}</span><span>Remaining: {money(Math.max(0,p.amount-p.paidAmount))}</span><span>Due: {p.due||'—'}</span><span>Paid date: {p.paid||'—'}</span><span>Method: {p.method}</span></div></article>)}{!data.payments.length&&<Empty text="No payments have been linked to your account yet."/>}</div>;}
function Profile({data,mutate}:{data:PortalData;mutate:Mutate}){const [form,setForm]=useState(data.profile),[message,setMessage]=useState(''),[pending,setPending]=useState(false);return <div className="grid gap-5 xl:grid-cols-2"><form className={`${card} grid gap-4`} onSubmit={async e=>{e.preventDefault();setPending(true);try{await mutate('profile',form);setMessage('Contact details saved.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.');}finally{setPending(false);}}}><h2 className="font-display text-xl font-bold">{data.account?.company}</h2>{(['name','email','phone','website','address'] as const).map(k=><Input key={k} label={k==='name'?'Primary contact':k[0].toUpperCase()+k.slice(1)} value={form[k]} type={k==='email'?'email':k==='website'?'url':'text'} onChange={v=>setForm(f=>({...f,[k]:v}))}/>)}{!data.employee&&<button disabled={pending} className={`${button} bg-brand`}>{pending?'Saving…':'Save contact details'}</button>}{data.employee&&<p className="text-xs text-zinc-500">Use the CRM Clients tab to edit company contact details.</p>}{message&&<p role="status" className="text-sm text-brand-light">{message}</p>}</form><div className="space-y-5"><div className={card}><h2 className="font-display text-xl font-bold">Your account manager</h2><p className="mt-3">{data.manager?.name||'Your DCampaign team'}</p>{data.manager&&<p className="mt-1 break-all text-sm text-zinc-400">{data.manager.email}</p>}</div><div className={card}><h2 className="font-display text-xl font-bold">Services</h2>{data.services.map((s,i)=><div className="mt-4 border-t border-white/5 pt-3" key={i}><b className="text-sm">{s.name}</b><p className="mt-1 text-xs text-zinc-400">{s.status} · Started {s.start||'—'}</p></div>)}</div></div></div>;}

function Access({data,mutate,initialClientId}:{data:PortalData;mutate:Mutate;initialClientId?:string}){
 const [clientId,setClientId]=useState(initialClientId||data.account?.crm_client_id||data.clients[0]?.id||''),[managerId,setManagerId]=useState(data.account?.manager_id||''),[active,setActive]=useState(data.account?.is_active??true),[name,setName]=useState(''),[email,setEmail]=useState(''),[message,setMessage]=useState(''),[pending,setPending]=useState(false);
 const run=async(action:string,input:unknown)=>{setPending(true);setMessage('');try{await mutate(action,input);setMessage(action==='invite'?'Access linked. New accounts receive a password setup invitation; existing accounts use their current password.':'Portal access saved.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.');}finally{setPending(false);}};
 return <div className="space-y-5"><form className={`${card} grid gap-4 sm:grid-cols-2`} onSubmit={e=>{e.preventDefault();void run('access',{clientId,managerId:managerId||null,active});}}><h2 className="font-display text-xl font-bold sm:col-span-2">Create / manage portal access</h2><label className="grid gap-1 text-xs text-zinc-400">Client company<select className={field} required value={clientId} onChange={e=>{setClientId(e.target.value);const a=data.accounts.find(a=>a.crm_client_id===e.target.value);setManagerId(a?.manager_id||'');setActive(a?.is_active??true);}}><option value="">Select client</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.company}</option>)}</select></label><label className="grid gap-1 text-xs text-zinc-400">Account manager<select className={field} value={managerId} onChange={e=>setManagerId(e.target.value)}><option value="">Unassigned</option>{data.managers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/> Portal active</label><button disabled={pending||!clientId} className={`${button} bg-brand`}>Save portal access</button></form>
 {data.account&&<><form className={`${card} grid gap-4 sm:grid-cols-2`} onSubmit={e=>{e.preventDefault();void run('invite',{accountId:data.account?.id,name,email});}}><h2 className="font-display text-xl font-bold sm:col-span-2">Invite to {data.account.company}</h2><Input label="Contact name" value={name} onChange={setName} required/><Input label="Email" value={email} onChange={setEmail} type="email" required/><p className="text-xs text-zinc-500 sm:col-span-2">New clients receive a secure invitation to set their own password. A company can have multiple contacts.</p><button disabled={pending||!data.account.is_active} className={`${button} bg-brand sm:col-span-2`}>Create portal access / send invitation</button></form><div className={card}><h2 className="font-display text-xl font-bold">Portal contacts</h2>{data.members.map(m=><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t border-white/5 pt-4" key={m.id}><div><b className="text-sm">{m.name}</b><p className="text-xs text-zinc-500">{m.email}</p></div><button disabled={pending} className={button} onClick={()=>void run('member',{id:m.id,active:!m.is_active})}>{m.is_active?'Disable access':'Enable access'}</button></div>)}{!data.members.length&&<p className="mt-3 text-sm text-zinc-500">No contacts invited yet.</p>}</div></>}
 {message&&<p role="status" className="rounded-xl border border-white/10 p-3 text-sm text-brand-light">{message}</p>}
 </div>;
}
