import Link from 'next/link';
import { redirect } from 'next/navigation';
import { PortalShell, type PortalService } from '@/components/portal/portal-shell';
import { getCurrentClientContext } from '@/lib/queries/client-context';

type Project = { id: string; title: string; status: string; progress: number; due_date: string | null };
type Task = { id: string; title: string; status: string; due_date: string | null };
type Activity = { id: string; title: string; description: string | null; created_at: string };
type Approval = { id: string; title: string; due_date: string | null };
type Report = { id: string; title: string; report_type: string; created_at: string };

function StatCard({ label, value, note }: { label: string; value: string | number; note?: string }) {
  return <div className="rounded-2xl border border-white/8 bg-white/[0.035] p-5"><p className="text-sm font-extrabold uppercase tracking-[0.16em] text-white/45">{label}</p><p className="mt-3 font-display text-3xl font-extrabold tracking-tight">{value}</p>{note && <p className="mt-1 text-sm text-white/45">{note}</p>}</div>;
}

function EmptyState({ title, body, href, action }: { title: string; body: string; href?: string; action?: string }) {
  return <div className="rounded-2xl border border-dashed border-white/12 bg-white/[0.02] p-6"><p className="font-display text-lg font-bold">{title}</p><p className="mt-2 max-w-xl text-sm leading-6 text-white/50">{body}</p>{href && action && <Link href={href} className="mt-4 inline-flex min-h-11 items-center text-sm font-extrabold text-brand-light hover:text-white">{action} →</Link>}</div>;
}

export default async function ClientDashboardPage() {
  const context = await getCurrentClientContext();
  if (!context.user) redirect('/client/login');
  if (!context.supabase || !context.clientId || !context.client || !context.profile) {
    return <main className="grid min-h-screen place-items-center bg-brand-bg px-6 text-white"><div className="glass-card max-w-xl rounded-3xl p-8"><p className="text-sm font-extrabold uppercase tracking-widest text-brand">Account setup</p><h1 className="mt-3 font-display text-3xl font-extrabold">Your workspace is being prepared.</h1><p className="mt-4 text-base leading-7 text-white/55">Your login is valid, but it is not linked to a client organization yet. Ask your DCampaign account manager to complete the invitation.</p></div></main>;
  }
  const { supabase, clientId } = context;
  const [projectsResult, tasksResult, activityResult, approvalsResult, reportsResult, invoicesResult, notificationsResult] = await Promise.all([
    supabase.from('projects').select('id,title,status,progress,due_date').eq('client_id', clientId).order('updated_at', { ascending: false }).limit(6),
    supabase.from('tasks').select('id,title,status,due_date').eq('client_id', clientId).eq('visible_to_client', true).in('status', ['in_progress', 'planned', 'awaiting_client']).order('due_date', { ascending: true, nullsFirst: false }).limit(6),
    supabase.from('activities').select('id,title,description,created_at').eq('client_id', clientId).eq('visible_to_client', true).order('created_at', { ascending: false }).limit(6),
    supabase.from('approvals').select('id,title,due_date').eq('client_id', clientId).eq('status', 'pending').order('due_date', { ascending: true, nullsFirst: false }).limit(5),
    supabase.from('reports').select('id,title,report_type,created_at').eq('client_id', clientId).eq('visible_to_client', true).order('created_at', { ascending: false }).limit(4),
    supabase.from('invoices').select('id,status,total').eq('client_id', clientId).in('status', ['issued', 'overdue']),
    supabase.from('notifications').select('*', { count: 'exact', head: true }).eq('profile_id', context.profile.id).is('read_at', null),
  ]);
  const projects = (projectsResult.data ?? []) as Project[];
  const tasks = (tasksResult.data ?? []) as Task[];
  const activities = (activityResult.data ?? []) as Activity[];
  const approvals = (approvalsResult.data ?? []) as Approval[];
  const reports = (reportsResult.data ?? []) as Report[];
  const activeProjects = projects.filter((project) => !['completed', 'cancelled'].includes(project.status));
  const services = context.services as PortalService[];
  return (
    <PortalShell companyName={context.client.company_name} packageName={context.client.package_name} profileName={context.profile.full_name} services={services} pendingApprovals={approvals.length} unreadNotifications={notificationsResult.count ?? 0}>
      <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-extrabold uppercase tracking-[0.2em] text-brand">Client dashboard</p><h1 className="mt-3 font-display text-4xl font-extrabold tracking-[-0.035em] sm:text-5xl">Welcome, {context.profile.full_name.split(' ')[0]}.</h1><p className="mt-3 text-base text-white/50">A clear view of what your DCampaign team is moving forward.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-2 text-sm font-bold text-emerald-300"><span className="size-2 rounded-full bg-emerald-300" /> {context.client.status === 'active' ? 'Account on track' : String(context.client.status).replace('_', ' ')}</span></div>
      <div className="mt-9 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Active services" value={services.length} /><StatCard label="Active projects" value={activeProjects.length} /><StatCard label="Awaiting you" value={approvals.length + tasks.filter((task) => task.status === 'awaiting_client').length} /><StatCard label="Open invoices" value={invoicesResult.data?.length ?? 0} /></div>
      <section className="mt-8"><div className="mb-5 flex items-end justify-between gap-4"><div><p className="text-sm font-extrabold uppercase tracking-widest text-brand">Services</p><h2 className="mt-2 font-display text-2xl font-extrabold">Your active growth stack</h2></div></div>{services.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{services.map((service) => <div key={service.id} className="rounded-2xl border border-white/8 bg-white/[0.03] p-5"><div className="flex items-center justify-between gap-3"><p className="font-bold">{service.name}</p><span className="text-sm font-extrabold text-brand-light">{service.progress}%</span></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-brand" style={{ width: `${service.progress}%` }} /></div><p className="mt-3 text-sm capitalize text-white/45">{service.status}</p></div>)}</div> : <EmptyState title="No services assigned yet" body="Services appear here as soon as your DCampaign team activates them for your organization." />}</section>
      <div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-3xl border border-white/8 bg-white/[0.025] p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-extrabold uppercase tracking-widest text-brand">Projects</p><h2 className="mt-2 font-display text-2xl font-extrabold">Delivery progress</h2></div><span className="text-xs font-bold uppercase tracking-wider text-white/35">Live view</span></div><div className="mt-6 space-y-4">{activeProjects.length ? activeProjects.slice(0,4).map((project) => <Link href={`/client/projects/${project.id}`} key={project.id} className="block rounded-2xl border border-white/8 p-4 transition hover:border-brand/35"><div className="flex justify-between gap-4"><p className="font-bold">{project.title}</p><span className="text-sm text-white/50">{project.progress}%</span></div><div className="mt-3 h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-brand" style={{ width: `${project.progress}%` }} /></div></Link>) : <EmptyState title="No active projects" body="Project timelines and milestones will appear here when work begins." />}</div></section>
      <section className="rounded-3xl border border-white/8 bg-white/[0.025] p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-extrabold uppercase tracking-widest text-brand">Current work</p><h2 className="mt-2 font-display text-2xl font-extrabold">What is moving now</h2></div></div><div className="mt-6 space-y-3">{tasks.length ? tasks.map((task) => <div key={task.id} className="flex items-center justify-between gap-4 rounded-xl border border-white/8 px-4 py-3"><div><p className="text-sm font-bold">{task.title}</p><p className="mt-1 text-xs capitalize text-white/40">{task.status.replace('_', ' ')}</p></div>{task.due_date && <span className="text-xs text-white/40">{task.due_date}</span>}</div>) : <EmptyState title="No current tasks" body="There is nothing requiring attention right now." />}</div></section></div>
      <div className="mt-6 grid gap-6 xl:grid-cols-[1.1fr_0.9fr]"><section className="rounded-3xl border border-white/8 bg-white/[0.025] p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-extrabold uppercase tracking-widest text-brand">Recent activity</p><h2 className="mt-2 font-display text-2xl font-extrabold">Latest account updates</h2></div><span className="text-xs font-bold uppercase tracking-wider text-white/35">Live view</span></div><div className="mt-6 space-y-4">{activities.length ? activities.map((item) => <div key={item.id} className="border-b border-white/8 pb-4 last:border-0"><p className="font-bold">{item.title}</p><p className="mt-1 text-sm text-white/45">{item.description || new Intl.DateTimeFormat('en-IN', { dateStyle: 'medium' }).format(new Date(item.created_at))}</p></div>) : <EmptyState title="No activity yet" body="Verified updates from your team will build a timeline here." />}</div></section>
      <section className="rounded-3xl border border-white/8 bg-white/[0.025] p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-extrabold uppercase tracking-widest text-brand">Approvals</p><h2 className="mt-2 font-display text-2xl font-extrabold">Waiting for your review</h2></div><span className="text-xs font-bold uppercase tracking-wider text-white/35">Live view</span></div><div className="mt-6 space-y-3">{approvals.length ? approvals.map((item) => <Link href="/client/approvals" key={item.id} className="block rounded-xl border border-brand/20 bg-brand/[0.05] p-4 text-sm font-bold transition hover:border-brand/50">{item.title}</Link>) : <EmptyState title="You are all caught up" body="New creative, content, or project decisions will appear here." />}</div></section></div>
      <section className="mt-6 rounded-3xl border border-white/8 bg-white/[0.025] p-6"><div className="flex items-center justify-between"><div><p className="text-sm font-extrabold uppercase tracking-widest text-brand">Latest reports</p><h2 className="mt-2 font-display text-2xl font-extrabold">Performance, documented</h2></div><span className="text-xs font-bold uppercase tracking-wider text-white/35">Live view</span></div>{reports.length ? <div className="mt-6 grid gap-3 md:grid-cols-2">{reports.map((report) => <Link href="/client/reports" key={report.id} className="rounded-2xl border border-white/8 p-4 transition hover:border-brand/35"><p className="font-bold">{report.title}</p><p className="mt-1 text-xs uppercase tracking-wider text-white/40">{report.report_type}</p></Link>)}</div> : <div className="mt-6"><EmptyState title="Reports will appear here" body="Monthly and campaign reports become available after your team publishes them." /></div>}</section>
    </PortalShell>
  );
}

