import Image from 'next/image';
import Link from 'next/link';

const services = [
  ['SEO', '72%', 'bg-brand'],
  ['Social Media', '60%', 'bg-violet-400'],
  ['Meta Ads', '84%', 'bg-sky-400'],
  ['Website Development', '92%', 'bg-emerald-400'],
] as const;

const activities = [
  ['02 Sep', 'Meta campaign optimised', 'Performance Marketing Team', '2:42 PM'],
  ['01 Sep', 'SEO blog published', 'Content Team', '12:20 PM'],
  ['30 Aug', 'Instagram reel uploaded', 'Social Media Team', '4:08 PM'],
  ['29 Aug', 'Landing page updated', 'Web Team', '11:16 AM'],
] as const;

const documents = [
  ['August Performance Report', 'REPORT', 'Download'],
  ['SEO Audit', 'STRATEGY', 'Download'],
  ['Content Calendar', 'CONTENT', 'View'],
  ['Ad Creative Report', 'CREATIVE', 'View'],
  ['Invoice · August', 'BILLING', 'Download'],
] as const;

function Metric({ label, value, change }: { label: string; value: string; change?: string }) {
  return <div className="rounded-2xl border border-white/8 bg-white/[0.035] p-5"><p className="text-[0.65rem] font-extrabold uppercase tracking-[0.18em] text-white/40">{label}</p><p className="mt-3 font-display text-2xl font-extrabold tracking-tight text-white">{value}</p>{change && <p className="mt-1 text-xs font-semibold text-emerald-300">{change}</p>}</div>;
}

export default function ClientDashboardPage() {
  return (
    <main className="min-h-screen bg-brand-bg text-white">
      <header className="sticky top-0 z-30 border-b border-white/8 bg-brand-bg/90 backdrop-blur-xl"><div className="mx-auto flex h-18 max-w-[1440px] items-center justify-between px-5 sm:px-8"><Link href="/client/dashboard" aria-label="DCampaign dashboard"><Image src="/dcampaign-logo-white.webp" alt="DCampaign" width={167} height={32} priority className="h-7 w-auto" /></Link><div className="flex items-center gap-4"><div className="hidden text-right sm:block"><p className="text-xs font-bold">ABC Company</p><p className="text-[0.65rem] uppercase tracking-wider text-white/35">Growth Plan</p></div><div className="grid size-10 place-items-center rounded-full bg-brand font-display text-sm font-extrabold">AC</div></div></div></header>
      <div className="mx-auto grid max-w-[1440px] lg:grid-cols-[240px_minmax(0,1fr)]">
        <aside className="hidden border-r border-white/8 px-5 py-8 lg:block"><p className="mb-5 px-3 text-[0.62rem] font-extrabold uppercase tracking-[0.22em] text-white/30">Workspace</p><nav className="space-y-1 text-sm"><a href="#overview" className="flex items-center gap-3 rounded-xl bg-brand/15 px-3 py-3 font-bold text-brand-light">Overview</a><Link href="/client/projects" className="flex items-center gap-3 rounded-xl px-3 py-3 font-semibold text-white/45 transition hover:bg-white/5 hover:text-white">Projects</Link>{['SEO', 'Meta Ads', 'Social Media', 'Website', 'Reports', 'Files', 'Approvals', 'Invoices', 'Support'].map((item) => <a key={item} href={`#${item.toLowerCase().replace(' ', '-')}`} className="flex items-center justify-between rounded-xl px-3 py-3 font-semibold text-white/45 transition hover:bg-white/5 hover:text-white"><span>{item}</span>{item === 'Approvals' && <span className="rounded-full bg-brand px-2 py-0.5 text-[0.6rem] text-white">3</span>}</a>)}<Link href="/client/activity" className="flex items-center justify-between rounded-xl px-3 py-3 font-semibold text-white/45 transition hover:bg-white/5 hover:text-white">Activity</Link></nav><div className="mt-10 border-t border-white/8 pt-6"><a href="/" className="px-3 text-xs font-bold uppercase tracking-wider text-white/30 hover:text-brand-light">← Portal home</a></div></aside>
        <section id="overview" className="min-w-0 px-5 py-8 sm:px-8 lg:px-10 lg:py-10"><div className="mb-9 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-[0.65rem] font-extrabold uppercase tracking-[0.22em] text-brand">Client dashboard</p><h1 className="mt-3 font-display text-4xl font-extrabold tracking-[-0.035em] sm:text-5xl">Hi, ABC Company <span aria-hidden="true">👋</span></h1><p className="mt-3 text-sm text-white/45">Here’s what your growth team moved forward this month.</p></div><span className="inline-flex w-fit items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/10 px-3 py-2 text-[0.65rem] font-extrabold uppercase tracking-wider text-emerald-300"><span className="size-1.5 rounded-full bg-emerald-300" /> Account on track</span></div>
          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{services.map(([name, progress, color]) => <div key={name} className="rounded-2xl border border-white/8 bg-white/[0.035] p-5"><div className="flex items-start justify-between gap-3"><p className="text-sm font-bold">{name}</p><span className="font-display text-lg font-extrabold text-white">{progress}</span></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-white/10"><div className={`h-full rounded-full ${color}`} style={{ width: progress }} /></div><p className="mt-3 text-[0.65rem] uppercase tracking-wider text-white/35">Project progress</p></div>)}</div>
          <div className="mt-10 grid gap-6 xl:grid-cols-[1.15fr_0.85fr]"><section className="rounded-3xl border border-white/8 bg-white/[0.025] p-6 sm:p-8"><div className="mb-7 flex items-center justify-between"><div><p className="text-[0.65rem] font-extrabold uppercase tracking-[0.2em] text-brand">This month</p><h2 className="mt-2 font-display text-2xl font-extrabold">SEO delivery</h2></div><a href="#seo" className="text-xs font-bold uppercase tracking-wider text-brand-light hover:text-white">View details ↗</a></div><div className="grid gap-3 sm:grid-cols-2">{['Technical audit', '12 keywords optimised', '4 blog articles', '28 backlinks'].map((task) => <div key={task} className="flex items-center gap-3 rounded-xl border border-white/8 bg-white/[0.03] px-4 py-3 text-sm font-semibold text-white/75"><span className="grid size-5 place-items-center rounded-full bg-emerald-400/15 text-xs text-emerald-300">✓</span>{task}</div>)}{['Schema implementation', 'Core Web Vitals improvement'].map((task) => <div key={task} className="flex items-center gap-3 rounded-xl border border-white/6 px-4 py-3 text-sm font-semibold text-white/35"><span className="grid size-5 place-items-center rounded-full border border-white/15 text-xs">○</span>{task}</div>)}</div></section><section className="rounded-3xl border border-white/8 bg-white/[0.025] p-6 sm:p-8"><p className="text-[0.65rem] font-extrabold uppercase tracking-[0.2em] text-brand">Meta ads</p><div className="mt-2 flex items-end justify-between gap-4"><h2 className="font-display text-2xl font-extrabold">August performance</h2><span className="text-xs font-bold text-emerald-300">4.38x ROAS</span></div><div className="mt-7 grid grid-cols-2 gap-3"><Metric label="Spend" value="₹42,560" /><Metric label="Revenue" value="₹1,86,400" change="↑ 18.4%" /><Metric label="Leads" value="124" change="↑ 22 this month" /><Metric label="CPL" value="₹343" /></div></section></div>
          <div className="mt-6 grid gap-6 xl:grid-cols-[0.9fr_1.1fr]"><section className="rounded-3xl border border-white/8 bg-white/[0.025] p-6 sm:p-8"><p className="text-[0.65rem] font-extrabold uppercase tracking-[0.2em] text-brand">Social media</p><h2 className="mt-2 font-display text-2xl font-extrabold">Audience momentum</h2><div className="mt-7 grid grid-cols-2 gap-3"><Metric label="Posts published" value="14" /><Metric label="Reels published" value="8" /><Metric label="Reach" value="128K" change="↑ 32%" /><Metric label="Engagement" value="7.8%" /></div></section><section className="rounded-3xl border border-white/8 bg-white/[0.025] p-6 sm:p-8"><div className="mb-6 flex items-center justify-between"><div><p className="text-[0.65rem] font-extrabold uppercase tracking-[0.2em] text-brand">Recent activity</p><h2 className="mt-2 font-display text-2xl font-extrabold">Work, in one timeline.</h2></div><a href="#activity" className="text-xs font-bold uppercase tracking-wider text-brand-light hover:text-white">All activity ↗</a></div><div className="space-y-4">{activities.map(([date, title, team, time]) => <div key={`${date}-${title}`} className="flex gap-4 border-b border-white/6 pb-4 last:border-0 last:pb-0"><span className="w-14 shrink-0 text-[0.65rem] font-bold uppercase tracking-wider text-white/30">{date}</span><div className="min-w-0"><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs text-white/35">{team} · {time}</p></div></div>)}</div></section></div>
          <section className="mt-6 rounded-3xl border border-white/8 bg-white/[0.025] p-6 sm:p-8"><div className="mb-6 flex items-center justify-between"><div><p className="text-[0.65rem] font-extrabold uppercase tracking-[0.2em] text-brand">Documents</p><h2 className="mt-2 font-display text-2xl font-extrabold">Your latest files.</h2></div><a href="#files" className="text-xs font-bold uppercase tracking-wider text-brand-light hover:text-white">View all ↗</a></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{documents.map(([name, type, action]) => <a href="#files" key={name} className="flex items-center justify-between gap-3 rounded-2xl border border-white/8 bg-white/[0.03] p-4 transition hover:border-brand/30 hover:bg-brand/[0.04]"><div className="min-w-0"><p className="truncate text-sm font-bold">{name}</p><p className="mt-1 text-[0.6rem] font-extrabold uppercase tracking-[0.18em] text-white/30">{type}</p></div><span className="shrink-0 text-[0.65rem] font-extrabold uppercase tracking-wider text-brand-light">{action} ↓</span></a>)}</div></section>
        </section>
      </div>
    </main>
  );
}
