import { NextResponse } from 'next/server';
import { z } from 'zod';
import { createSupabaseAdminClient } from '@/lib/supabase/admin';
import { createSupabaseServerClient } from '@/lib/supabase/server';

const roles = ['super_admin','admin','sales','account_manager','team_member','finance'] as const;
const createSchema = z.object({fullName:z.string().trim().min(2).max(120),email:z.string().trim().email().max(200),role:z.enum(roles),password:z.string().min(8).max(128)});
const updateSchema = z.object({id:z.string().uuid(),fullName:z.string().trim().min(2).max(120),email:z.string().trim().email().max(200),role:z.enum(roles),password:z.string().min(8).max(128).optional().or(z.literal('')),isActive:z.boolean().default(true)});

async function context(){const auth=await createSupabaseServerClient();if(!auth)return null;const {data:{user}}=await auth.auth.getUser();if(!user)return null;const admin=createSupabaseAdminClient();const {data:profile}=await admin.from('profiles').select('id,user_id,role,is_active').eq('user_id',user.id).maybeSingle();if(!profile?.is_active||!['super_admin','admin'].includes(profile.role))return null;return {admin,profile}}

export async function GET(){const ctx=await context();if(!ctx)return NextResponse.json({error:'Unauthorized'},{status:401});const {data,error}=await ctx.admin.from('profiles').select('id,user_id,full_name,email,role,is_active,created_at,updated_at').neq('role','client').order('created_at');if(error)return NextResponse.json({error:'Unable to load team members.'},{status:500});return NextResponse.json({members:data})}

export async function POST(request:Request){const ctx=await context();if(!ctx)return NextResponse.json({error:'Unauthorized'},{status:401});const parsed=createSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Enter a valid name, email, role, and password of at least 8 characters.'},{status:400});if(parsed.data.role==='super_admin'&&ctx.profile.role!=='super_admin')return NextResponse.json({error:'Only a super administrator can create another super administrator.'},{status:403});const {data,error}=await ctx.admin.auth.admin.createUser({email:parsed.data.email,password:parsed.data.password,email_confirm:true,user_metadata:{full_name:parsed.data.fullName}});if(error||!data.user)return NextResponse.json({error:error?.message||'Unable to create team member.'},{status:400});const {error:profileError}=await ctx.admin.from('profiles').upsert({user_id:data.user.id,full_name:parsed.data.fullName,email:parsed.data.email,role:parsed.data.role,is_active:true},{onConflict:'user_id'});if(profileError){await ctx.admin.auth.admin.deleteUser(data.user.id);return NextResponse.json({error:'Unable to create the team profile.'},{status:500})}return NextResponse.json({ok:true})}

export async function PATCH(request:Request){const ctx=await context();if(!ctx)return NextResponse.json({error:'Unauthorized'},{status:401});const parsed=updateSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Invalid team member details.'},{status:400});const {data:target}=await ctx.admin.from('profiles').select('user_id,role').eq('id',parsed.data.id).maybeSingle();if(!target)return NextResponse.json({error:'Team member not found.'},{status:404});if((target.role==='super_admin'||parsed.data.role==='super_admin')&&ctx.profile.role!=='super_admin')return NextResponse.json({error:'Only a super administrator can modify this account.'},{status:403});const authUpdate:{email:string;user_metadata:{full_name:string};password?:string}={email:parsed.data.email,user_metadata:{full_name:parsed.data.fullName}};if(parsed.data.password)authUpdate.password=parsed.data.password;const {error:authError}=await ctx.admin.auth.admin.updateUserById(target.user_id,authUpdate);if(authError)return NextResponse.json({error:authError.message},{status:400});const {error}=await ctx.admin.from('profiles').update({full_name:parsed.data.fullName,email:parsed.data.email,role:parsed.data.role,is_active:parsed.data.isActive,updated_at:new Date().toISOString()}).eq('id',parsed.data.id);if(error)return NextResponse.json({error:'Unable to update team member.'},{status:500});return NextResponse.json({ok:true})}

export async function DELETE(request:Request){const ctx=await context();if(!ctx)return NextResponse.json({error:'Unauthorized'},{status:401});const id=new URL(request.url).searchParams.get('id');if(!id)return NextResponse.json({error:'Team member ID is required.'},{status:400});const {data:target}=await ctx.admin.from('profiles').select('user_id,role').eq('id',id).maybeSingle();if(!target)return NextResponse.json({error:'Team member not found.'},{status:404});if(target.user_id===ctx.profile.user_id)return NextResponse.json({error:'You cannot delete your own account.'},{status:400});if(target.role==='super_admin'&&ctx.profile.role!=='super_admin')return NextResponse.json({error:'Only a super administrator can delete this account.'},{status:403});const {error}=await ctx.admin.auth.admin.deleteUser(target.user_id);if(error)return NextResponse.json({error:error.message},{status:400});return NextResponse.json({ok:true})}
