import Link from 'next/link';
import { createSupabaseServerClient } from '@/lib/supabase/server';

export default async function ClientProjectsPage() {
  const supabase = await createSupabaseServerClient();
  const projects = supabase ? (await supabase.from('projects').select('id,title,status,progress,due_date,priority,services(name)').order('updated_at', { ascending: false })).data ?? [] : [];
  return <main className="min-h-screen bg-brand-bg px-6 pb-20 pt-28 text-white md:px-12"><div className="mx-auto max-w-7xl"><Link href="/client/dashboard" className="text-sm font-bold uppercase tracking-widest text-brand-light hover:text-white">← Dashboard</Link><p className="mt-10 text-sm font-extrabold uppercase tracking-widest text-brand">Project delivery</p><h1 className="mt-3 font-display text-4xl font-extrabold tracking-tight md:text-5xl">Work in progress.</h1><p className="mt-3 max-w-2xl text-base leading-7 text-white/55">Follow every active project, milestone, and next delivery from your DCampaign team.</p><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{projects.length === 0 ? <EmptyState /> : projects.map((project) => { const serviceRelation = project.services; const service = Array.isArray(serviceRelation) ? serviceRelation[0] : serviceRelation; return <Link key={project.id} href={`/client/projects/${project.id}`} className="glass-card rounded-2xl p-6 transition hover:-translate-y-1 hover:border-brand/40"><div className="flex items-start justify-between gap-3"><p className="text-sm font-extrabold uppercase tracking-widest text-brand">{service?.name ?? 'Project'}</p><span className="rounded-full bg-white/8 px-2.5 py-1 text-xs font-bold uppercase tracking-wider text-white/60">{String(project.status).replace('_',' ')}</span></div><h2 className="mt-5 font-display text-xl font-extrabold">{project.title}</h2><div className="mt-7 h-1.5 rounded-full bg-white/10"><div className="h-full rounded-full bg-brand" style={{ width: `${project.progress}%` }} /></div><div className="mt-3 flex justify-between text-sm text-white/45"><span>{project.progress}% complete</span><span>{project.due_date ? `Due ${project.due_date}` : 'No due date'}</span></div></Link>})}</div></div></main>;
}

function EmptyState() { return <div className="glass-card rounded-2xl p-8 md:col-span-2 xl:col-span-3"><h2 className="font-display text-xl font-extrabold">Projects will appear here.</h2><p className="mt-2 text-sm leading-7 text-white/45">Once your DCampaign team assigns a project to your account, its progress and milestones will be available in this workspace.</p></div>; }
