import Link from 'next/link';
import { notFound } from 'next/navigation';
import { createSupabaseServerClient } from '@/lib/supabase/server';

export default async function ClientProjectDetail({ params }: { params: Promise<{ projectId: string }> }) {
  const { projectId } = await params;
  const supabase = await createSupabaseServerClient();
  if (!supabase) notFound();
  const { data: project } = await supabase.from('projects').select('id,title,description,status,progress,due_date,priority,project_milestones(id,title,status,progress,due_date,display_order),tasks(id,title,status,due_date,visible_to_client)').eq('id', projectId).single();
  if (!project) notFound();
  const visibleTasks = (project.tasks ?? []).filter((task) => task.visible_to_client);
  return <main className="min-h-screen bg-brand-bg px-6 pb-20 pt-28 text-white md:px-12"><div className="mx-auto max-w-5xl"><Link href="/client/projects" className="text-xs font-bold uppercase tracking-widest text-brand-light hover:text-white">← All projects</Link><div className="mt-10 flex flex-col justify-between gap-5 border-b border-white/10 pb-8 md:flex-row md:items-end"><div><p className="text-xs font-extrabold uppercase tracking-widest text-brand">Project overview</p><h1 className="mt-3 font-display text-4xl font-extrabold md:text-5xl">{project.title}</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-white/45">{project.description ?? 'Your DCampaign project delivery and next milestones.'}</p></div><span className="rounded-full border border-brand/30 bg-brand/10 px-4 py-2 text-xs font-bold uppercase tracking-wider text-brand-light">{String(project.status).replace('_',' ')}</span></div><section className="mt-8 glass-card rounded-2xl p-6 md:p-8"><div className="flex justify-between text-sm font-bold"><span>Overall progress</span><span className="text-brand-light">{project.progress}%</span></div><div className="mt-4 h-2 rounded-full bg-white/10"><div className="h-full rounded-full bg-brand" style={{ width: `${project.progress}%` }} /></div></section><div className="mt-8 grid gap-8 lg:grid-cols-2"><section><p className="text-xs font-extrabold uppercase tracking-widest text-brand">Milestones</p><div className="mt-4 space-y-3">{(project.project_milestones ?? []).sort((a,b) => a.display_order-b.display_order).map((milestone) => <div key={milestone.id} className="glass-card rounded-xl p-5"><div className="flex justify-between gap-3"><h2 className="font-display font-bold">{milestone.title}</h2><span className="text-[0.6rem] font-bold uppercase tracking-wider text-white/40">{String(milestone.status).replace('_',' ')}</span></div><div className="mt-4 h-1 rounded bg-white/10"><div className="h-full rounded bg-brand" style={{width:`${milestone.progress}%`}} /></div></div>)}</div></section><section><p className="text-xs font-extrabold uppercase tracking-widest text-brand">Client-visible work</p><div className="mt-4 space-y-3">{visibleTasks.length === 0 ? <div className="glass-card rounded-xl p-5 text-sm text-white/45">No visible tasks yet.</div> : visibleTasks.map((task) => <div key={task.id} className="glass-card rounded-xl p-5"><div className="flex justify-between gap-3"><h2 className="font-display font-bold">{task.title}</h2><span className="text-[0.6rem] font-bold uppercase tracking-wider text-brand-light">{String(task.status).replace('_',' ')}</span></div>{task.due_date && <p className="mt-2 text-xs text-white/40">Due {task.due_date}</p>}</div>)}</div></section></div></div></main>;
}
